### ISSUE TITLE
zfs-auto-snapshot fails on transition to winter time

### ISSUE THREAD

**Issue by durandalTR** [zfsonlinux/pkg-zfs#100]
I found an edge case here. Last night was the transition from summer time to winter time so at 3am the clock was put back to 2am. 

<pre>cannot create snapshot 'tank@zfs-auto-snap_frequent-2013-10-27-0200': 
dataset already exists no snapshots were created</pre>

4 snapshots (every 15 mins between 2 and 3am (winter time) were not created as those times were already used in the filenames.

<pre>/etc/cron.hourly/zfs-auto-snapshot:
cannot create snapshot 'tank@zfs-auto-snap_hourly-2013-10-27-0217': 
dataset already exists no snapshots were created</pre>

1 hourly snapshot was not created either.

No other adverse effects observed.

**Comment by dajhorn** [comment]
This bug should be resolved by zfsonlinux/zfs-auto-snapshot#18, which makes UTC stamps the default.  The fix is committed to head but has not yet been tagged for release.

**Comment by dajhorn** [comment]
This bug should be resolved by the 1.1.0 release.
