### ISSUE TITLE
HOWTO install Ubuntu page absent

### ISSUE THREAD

**Issue by jeff-dagenais** [zfsonlinux/pkg-zfs#107]
Here's an easy one. On this project's wiki, top link, the infamous HowTo for ubuntu wiki page is missing.

Goto: https://github.com/zfsonlinux/pkg-zfs/wiki
Click the ubuntu how-to, it prompts a "create page" form.

**Comment by FransUrbo** [comment]
Works for me. Either fixed or temporary problem resolved.

**Comment by jeff-dagenais** [comment]
yep, confirmed, works now... I couldn't find a page revision change which explains it, except this line:

```
20 days ago:  Updated HOWTO install Ubuntu to a Native ZFS Root Filesystem (markdown) [df0c01b]
```

but the diff looks empty from the web "compare revisions" button. Weird. Anyway, it works now.
