### ISSUE TITLE
zfs-grub fails with -o ashift=12

### ISSUE THREAD

**Issue by olsner** [zfsonlinux/pkg-zfs#11]
Not sure if this is the proper place to report issues on the grub packages...

As per https://github.com/zfsonlinux/zfs/issues/348, there is a fix for this issue, but it doesn't appear to have made it into a package or the PPA yet.

**Comment by dajhorn** [comment]
That patch by @pendor does not apply to the current GRUB trunk.  After looking at the latest source code, I'm not sure whether upstream rewrote his fix or discarded it.

If you need to use GRUB on a pool with ashift=12, then you should compile it yourself.  I will look at it more thoroughly this week.

**Comment by dajhorn** [comment]
Okay, it seems that upstream is picky about submissions, and the important things are already in the Precise package.

You could probably build from the latest Ubuntu source package if you want a solution now.  Otherwise, I will build it for the PPA and do some testing this week.

**Comment by olsner** [comment]
The package from precise (assuming you meant the "vanilla" version in ubuntu's package repository) did not have the ashift fix. My pool was still not recognized as a zfs file system (with the same checksum errors as described in other places), and that was after applying brute hacks to the grub-probe code already to get it to figure out what device my file system was on.

I finally got it working by downloading the source package from the zfs PPA and applying @pendor's patch on top of it - just one three-line hunk that failed and had to be manually applied, otherwise a breeze.

**Comment by dajhorn** [comment]
If the ashift patch applied with only one bad chunk, then the debian/patches were not applied to the tree before build.

It sounds like you have a stock GRUB package.  Try doing this:

```
 # QUILT_PATCHES=debian/patches
 # quilt push -a
 # ./debian/rules binary
```

In my source tree, I get 13 bad chunks if I apply the ashift patch first.

**Comment by olsner** [comment]
Hmm, might I have managed to apply the ashift patch _under_ the debian patches or something then?

After downloading the .dsc, .orig.tar.gz and .diff.gz from the grub zfs PPA page (which was just before I realized that obviously there are already tools for downloading and unpacking source packages through apt...), I did something like this:

```
$ dpkg-source -x foo_version-revision.dsc
$ wget https://github.com/pendor/grub-zfs/commit/e7b6ef3ac3b9685ac4c394c897b1d4221b7381f1.diff
$ patch -p1 -i e7b6ef3ac3b9685ac4c394c897b1d4221b7381f1.diff
$ dpkg-buildpackage -rfakeroot -uc -b
```

And then I installed the debs it produced. The exact commands might vary a bit.

I wouldn't expect the result to work at all if I built a grub without _any_ debian patches... Neither should it work if I built without the ashift patch.

**Comment by dajhorn** [comment]
I tried it on both ends of the patch series, and got a large rejected chunk each time.

If you built with the ashift patch and it works, then no problem because grub rarely breaks after it is installed and left alone.  However, I need to completely rediff the whole package it before I publish it to the PPA for everybody.

**Comment by lembregtse** [comment]
Have you ever included this into the ppa? Just wondering so I can get this out of my list of possible problems why my grub is not booting.

**Comment by dajhorn** [comment]
No, this bug persists because the upstream GRUB maintainer refused or rewrote most of the ZFS fixes.  GRUB still randomly fails to boot from ZFS if the pool ashift is 12 or any other non-default value.

This bug could be fixed in the GRUB 2.00 alpha, but it is unlikely to be ready in time the Ubuntu 12.04 release.

**Comment by lembregtse** [comment]
Ok thanks for the response. Whenever this gets pushed I'll try it again, for now I've created seperate partitions to resolve the problem.

**Comment by olsner** [comment]
Tested the official grub 2.00 tarball and got a working grub-probe out of that, so I decided to do a trial upgrade to quantal and apparently grub 2.00-7ubuntu11 does work fine for my ashift=12 pool. (Well, after I added the magic words to the kernel command line to make the zfs initramfs stuff trigger properly.)
