### ISSUE TITLE
why use /boot/grub as partition label for boot?

### ISSUE THREAD

**Issue by bksunday** [zfsonlinux/pkg-zfs#110]
I try to be safe and avoid spaces and other characters.. but
`mke2fs -m 0 -L /boot/grub -j /dev/disk/by-id/some-disk-id`
specifies the full path as a label and not as a path.parameter, thus introducing slashes in names..

Is it needed by zfs?
`root@ubuntu:~# ls -l /dev/disk/by-label/`
`lrwxrwxrwx 1 root root 10 Apr  2 02:31 \x2fboot\x2fgrub -> ../../sda1`

**Comment by dajhorn** [comment]
> Is it needed by zfs?

No.

IIRC, this is in the ZoL documentation because the Ubuntu installer conventionally sets the mount point as the filesystem label.  Some systems use the `LABEL=` keyword instead of the `UUID=` keyword in the `/etc/fstab` file.
