### ISSUE TITLE
Update HOWTO install Ubuntu to a Native ZFS Root Filesystem to Ubuntu 14.04

### ISSUE THREAD

**Issue by fire** [zfsonlinux/pkg-zfs#114]
Please update the guide to Ubuntu 14.04. 

There are a few things that are different. Grub supports compressed zfs pools now.

**Comment by ElijahLynn** [comment]
Can you leave a list of all the things you know of to be different in this issue?

I am about to start testing out ZFS root on Ubuntu 14.04 and am going through the readme now. Combined with your tips I could make an edit or two on the page.

Or if you want to just edit the wiki directly here that would be good too => https://github.com/zfsonlinux/pkg-zfs/wiki/HOWTO-install-Ubuntu-to-a-Native-ZFS-Root-Filesystem

**Comment by fire** [comment]
- zfs-grub does not exist on Trusty
- Verify that compression=lz4 works or does not work
- (ZFS root) Mention you need to create a symbolic link to the device for grub-install to work (bug). See https://github.com/zfsonlinux/pkg-zfs/issues/113
- Debootstrap installs precise instead of Trusty
- In /etc/default/grub add "boot=zfs" to GRUB_CMDLINE_LINUX_DEFAULT=

**Comment by ElijahLynn** [comment]
Thanks, I didn't end up going through the whole process yet (work/priority) but when I do this will be very helpful!

**Comment by dajhorn** [comment]
This document was subsequently forked and updated by the ZoL user community, so I will close this ticket as stale and/or complete.
