### ISSUE TITLE
Debian Wheezy amd64 7.5 apt-get update & upgrade => zfsonlinux broken

### ISSUE THREAD

**Issue by dpchrist** [zfsonlinux/pkg-zfs#116]
zfsonlinux/pkg-zfs issue:

I have a machine running Debian Wheezy amd64 7.5.  This morning, I did:

```
# apt-get update
# apt-get upgrade
```

After rebooting, my ZFS on Linux pool and file systems no longer work:

```
# zpool list
no pools available

# zfs list
no datasets available
```

I believe the ZFS kernel module is loaded:

```
# dmesg | grep -i zfs
[   30.541398] ZFS: Loaded module v0.6.3-763_ge883253, ZFS pool
```

version 5000, ZFS filesystem version 5

I have a single ZFS pool that uses two disks in a mirror, and they appear
to be working:

```
# l /dev/mapper/ST*
/dev/mapper/ST3000DM001-9YN_S1F042HH_crypt@
/dev/mapper/ST3000DM001_1CH_W1F1R3VC_crypt@
```

Perhaps an additional clue:

```
# zpool import
zpool: ../../lib/libzfs/libzfs_import.c:356: Assertion `nvlist_lookup_uint64(zhp->zpool_config, ZPOOL_CONFIG_POOL_GUID, &theguid) == 0' failed.
Aborted
```

STFW I see posts about kernel module and userland mismatches (?):

```
https://github.com/zfsonlinux/zfs/issues/2400
```

One work-around seems to be manually unloading kernel modules, manually finding and removing various ZFS files, rebooting, and re-installing debian-zfs.  This is more complexity/ risk than I would like to undertake.

I am not adverse to wiping the system drive, doing a fresh install of Wheezy amd64 7.5, and doing a fresh install of debian-zfs.  If  I did so, would I be able to recover (import?) my ZFS pool?

The best solution would be for an update of http://archive.zfsonlinux.org/debian, I do an apt-get update & upgrade, reboot, and ZFS works again.

I need to resolve this problem in a timely fashion.  Please advise.

TIA,

David

**Comment by FransUrbo** [comment]
Well known, and announced _well in advance_ on the list:

https://groups.google.com/a/zfsonlinux.org/forum/#!searchin/zfs-discuss/Turbo$20Fredriksson%7Csort:date/zfs-discuss/jAMnJf_ve1A/s5NWdaxPKK8J

You should have issued <code>apt-get dist-upgrade</code>, not <code>apt-get upgrade</code>. And the pool will 'come back' after a reboot.

**Comment by dpchrist** [comment]
On 06/23/2014 01:55 AM, Turbo Fredriksson wrote:

> Well known, and announced _well in advance_ on the list:
> https://groups.google.com/a/zfsonlinux.org/forum/#!searchin/zfs-discuss/Turbo$20Fredriksson%7Csort:date/zfs-discuss/jAMnJf_ve1A/s5NWdaxPKK8J

Okay.  I believe I'm subscribed now.

> You should have issued <code>apt-get dist-upgrade</code>, not <code>apt-get upgrade</code>. And the pool will 'come back' after a reboot.

Problem solved -- thank you.  :-)

David
