### ISSUE TITLE
Exported pool disappeared from import list

### ISSUE THREAD

**Issue by startled** [zfsonlinux/pkg-zfs#117]
My ZFS pool stopped automatically mounting after booting around when I upgraded to Ubuntu 13.10. I started running through the instructions on this wiki page:
https://github.com/zfsonlinux/pkg-zfs/wiki/Ubuntu-ZFS-mountall-FAQ-and-troubleshooting

After checking the Frequent Mistakes section, I started in on the Troubleshooting instructions:

```
    # zpool export tank
    # rm /etc/zfs/zpool.cache
    # zpool import tank
    cannot import 'tank': no such pool available
```

Mild panic begins to set in:

```
    # zpool list tank
    cannot open 'tank': no such pool
    # zpool status
    no pools available
    # zpool import -a
    // No output
```

I don't have a lot of ZFS-fu, but here's what I've been trying:

```
    # zpool import tank -d /dev/disk/by-id/
    cannot import 'tank': no such pool available
    # zpool create -n tank /dev/disk/by-id/<long-disk-id>
    invalid vdev specification
    use '-f' to override the following errors:
    /dev/disk/by-id/<long-disk-id> is part of exported pool 'tank'
```

It's a little reassuring that zpool is unwilling to overwrite the devices because they are already part of a pool, but I'd really like it to be able to find that pool again.
I'd love to have mountall at startup working again, but right now any advice to get the pool restored would be very much appreciated. Thanks!

**Comment by FransUrbo** [comment]
This is really a support question and not a bug/issue. Please use the mailing list in the future.

You could try 'zpool import -D' to see if it's been 'destroyed'.
