### ISSUE TITLE
Unable to install ubuntu-zfs

### ISSUE THREAD

**Issue by OXYAMINE** [zfsonlinux/pkg-zfs#118]
Trying to install ubuntu-zfs package on ubuntu 13.04
and getting this error "E: Unable to locate package ubuntu-zfs"
PPA (http://ppa.launchpad.net/zfs-native/stable/ubuntu) was added.
apt-get updated.

**Comment by dajhorn** [comment]
The PPA does not have packages for Raring because it went out of support in January.  If you actually need ZoL for this Ubuntu release, then you should compile from source or try the Precise packages.

**Comment by OXYAMINE** [comment]
Getting "forbidden" error trying to use Precise packages...
"out of support" means that there will be no updates for software anymore, right? Surprised that it was just deleted.
