### ISSUE TITLE
provide an option to keep old modules during DKMS upgrades

### ISSUE THREAD

**Issue by dajhorn** [zfsonlinux/pkg-zfs#12]
The standard debconf template for DKMS modules removes old modules during package upgrades.

The option to keep old versions is especially important for systems that have a native ZFS root filesystem because DKMS removals cause initrd updates, which makes old kernels unbootable.

**Comment by dajhorn** [comment]
This is in the `/usr/lib/dkms/common.postinst` script:

```
#We never want to keep an older version side by side to prevent conflicts
if [ -e "/var/lib/dkms/$NAME/$VERSION" ]; then
    echo "Removing old $NAME-$VERSION DKMS files..."
    dkms remove -m $NAME -v $VERSION --all
fi
```

This means that the entire `dh_dkms` template must be overridden to implement this module retention.

**Comment by singpolyma** [comment]
Having old kernels continue to work seems essential. How hard would this change be? I it just copying in the scripts and removing the one part?

**Comment by dajhorn** [comment]
@singpolyma, the actual code patch would indeed be a small, but the policy conformance and integration would be a big job.

The primary DKMS patch for ZoL was accepted both upstream and downstream since this ticket was created, so any additional work should happen there.  I am, therefore, closing this ticket.

**Comment by singpolyma** [comment]
Which "upstream" should I be referring to? Thanks.

**Comment by dajhorn** [comment]
@singpolyma, the DKMS home page is: 
- http://linux.dell.com/dkms/
