### ISSUE TITLE
Cannot export pool 'rpool': pool in use

### ISSUE THREAD

**Issue by Baughn** [zfsonlinux/pkg-zfs#120]
I'm getting this message during shutdown, and - naturally - the system will not afterwards boot.

**Comment by Baughn** [comment]
"Fixed" by setting zfs_force=on, so the problem is as you'd expect. I'm not seeing any useful logs, though.

**Comment by FransUrbo** [comment]
Are you using ZFS as your root filesystem? What distribution and version of ZoL are you using and were did you get it (selfbuilt or dist package)?

**Comment by Baughn** [comment]
Debian stable (7.6), and I installed it by following the instructions on https://github.com/zfsonlinux/pkg-zfs/wiki/HOWTO-install-Debian-GNU-Linux-to-a-Native-ZFS-Root-Filesystem exactly.

**Comment by FransUrbo** [comment]
Ok, so you're using the stable packages. This is fixed in the somewhat-experimental "snapshot" packages...

**Comment by Baughn** [comment]
-right.

Don't suppose we could have a backport?

**Comment by FransUrbo** [comment]
We could, but I can't be bothered. Not important enough - it's just a warning and adding

   zfs_force=1

"solves" the problem. Besides, I (and the ZoL team) recommends running latest anyway. So go with the snapshots...

**Comment by FransUrbo** [comment]
I believe this to be fixed in the new <code>0.6.5</code> version which was released a week or so ago. It contain new, improved versions of the init scripts where this doesn't happen.
