### ISSUE TITLE
ubuntu utopic stable ppa missing package mountall

### ISSUE THREAD

**Issue by timothyham** [zfsonlinux/pkg-zfs#123]
My /etc/apt/preferences.d/pin-zfs-native has the proper pin:
Package: *
Pin: release o=LP-PPA-zfs-native-stable
Pin-Priority: 1001

But my apt cache policy doesn't show it:
mountall:
  Installed: 2.54build1
  Candidate: 2.54build1
  Version table:
 **\* 2.54build1 0
        500 http://mirror.math.ucdavis.edu/ubuntu/ utopic/main amd64 Packages
        100 /var/lib/dpkg/status

Maybe it's because the mountall package is not in the ppa? I see it in trusty, but not in utopic package listings:

https://launchpad.net/~zfs-native/+archive/ubuntu/stable?field.series_filter=utopic
vs
https://launchpad.net/~zfs-native/+archive/ubuntu/stable?field.series_filter=trusty

**Comment by Anteru** [comment]
There is a zfs-mountall package, with no installation candidate. As it is right now, upgrading from Ubuntu 14.04 to 14.10 will break automount of ZFS.

**Comment by dajhorn** [comment]
@timothyham, thanks for reporting the missing package.  The stable PPA is resynchronized, and these packages should appear soon:
- https://launchpad.net/~zfs-native/+archive/ubuntu/stable/+files/mountall_2.54build1-zfs1_amd64.deb
- https://launchpad.net/~zfs-native/+archive/ubuntu/stable/+files/mountall_2.54build1-zfs1_armhf.deb
- https://launchpad.net/~zfs-native/+archive/ubuntu/stable/+files/mountall_2.54build1-zfs1_i386.deb

**Comment by timothyham** [comment]
Awesome! Works for me now.
