### ISSUE TITLE
Ubuntu Trusty: zfs-linux 0.6.3-3~trusty changes zvol udev rules

### ISSUE THREAD

**Issue by JKDingwall** [zfsonlinux/pkg-zfs#125]
The latest build of the Ubuntu package (zfs-linux   0.6.3-3~trusty  Darik Horn (17 hours ago) ) changes the symlink path generated in 60-zvol.rules to be prefixed by zvol.  Suddenly everything that was mounted by /dev/<zpool>/<zvol> no longer works.  Although easily to solve is this changed ruleset going to be stable or was its introduction unintentional and it could get reverted in a future build?

**Comment by JKDingwall** [comment]
I found that the /dev/zvol link has always existed but 60-zvol.rules has changed from:

`KERNEL=="zd*" SUBSYSTEM=="block" ACTION=="add|change" PROGRAM="/lib/udev/zvol_id $tempnode" SYMLINK+="zvol/%c %c"`

to:

`KERNEL=="zd*" SUBSYSTEM=="block" ACTION=="add|change" PROGRAM="/lib/udev/zvol_id $tempnode" SYMLINK+="zvol/%c"`

So that the /dev/[zpool]/[zvol] link doesn't exist.  Adding the %c back on the end restores the previous behaviour.

**Comment by dajhorn** [comment]
> Although easily to solve is this changed ruleset going to be stable or was its introduction unintentional and it could get reverted in a future build?

The `/dev/[zpool]/[zvol]` form was deprecated and the change is intentional.  The PPA got it earlier than upstream in anticipation of some pending distro changes.

If you want to keep the compatibility symlinks, then copy the old rules file to `/etc/udev/rules.d/60-zvol.rules` and leave `/lib/udev/rules.d/60-zvol.rules` intact.

**Comment by dajhorn** [comment]
Given that this change was ultimately accepted, I will close this ticket.
