### ISSUE TITLE
please make sure the spl devel package for your distribution is installed then try again

### ISSUE THREAD

**Issue by dajhorn** [zfsonlinux/pkg-zfs#13]
The `/etc/kernel/header_postinst.d/dkms` run-part always tries to recompile ZFS before SPL, which causes this configure error:

```
 *** Please make sure the spl devel package for your distribution
 *** is installed then try again.  If that fails you can specify the
 *** location of the spl source with the '--with-spl=PATH' option.
```

This error is incorrect because most people will try to install spl-dev afterwards, and also spurious because DKMS will successfully retry the zfs-dkms package after spl-dkms is ready.

In the few cases where ZFS legitimately fails to compile, doing this usually resolves the problem:

```
 # apt-get install --reinstall spl-dkms
 # apt-get install --reinstall zfs-dkms
```

The proper solution here is to enhance DKMS to recognize module dependencies, or to combine the SPL and ZFS sources.

**Comment by Nowaker** [comment]
I got this error while updating to kernel 3.0.0-15.

**Comment by dajhorn** [comment]
This is adequately kludged in the debian patch series that is published to the daily PPA.

  https://github.com/dajhorn/pkg-zfs/tree/debian-patches
