### ISSUE TITLE
Ubuntu Trusty: zfs-linux 0.6.3-3~trusty missing arcstat.py

### ISSUE THREAD

**Issue by zrav** [zfsonlinux/pkg-zfs#131]
After installing the 0.6.3-3~trusty package arcstat.py is missing. Observed on multiple installations.

**Comment by dajhorn** [comment]
@zrav, thanks for opening an issue ticket. In the next point release, these files can be bundled with the other supporting scripts in `/usr/share/doc/zfs-doc/examples`.

The `arcstat.py` and `dbufstat.py` scripts aren't installed to avoid creating an automatic python dependency in the zfsutils package.  (This is also why these files are installed to `examples/` and not something like `libexec/`.)

Eventually, a zfs-contrib package should be created for such things.

**Comment by ser** [comment]
We have middle of 2015 and arcstat.py is still missing from examples.

**Comment by dajhorn** [comment]
Given that ZoL was imported to Ubuntu main, this ticket will be closed.
