### ISSUE TITLE
Ubuntu PPA will not work correctly in systemd

### ISSUE THREAD

**Issue by erkinalp** [zfsonlinux/pkg-zfs#132]
Installing native zfs tries to remove systemd as PID 1 and to install upstart instead on Ubuntu PPA package.

**Comment by erkinalp** [comment]
Steps to reproduce(PPA added previously):
apt install systemd-sysv upstart-
apt install ubuntu-zfs

**Comment by dajhorn** [comment]
The ubuntu-zfs metapackage will indirectly depend on upstart so long as mountall is an upstart job, or until mountall is replaced or retooled as a systemd unit.  Distro is likely to do this before the next LTS release.

**Comment by dajhorn** [comment]
For people interested in how Ubuntu will do its systemd migration:
- http://summit.ubuntu.com/uos-1411/meeting/22401/systemd-transition/

**Comment by samvde** [comment]
Cfr https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1432122 it seems mountall will disappear with systemd.

**Comment by erkinalp** [comment]
`systemd` handles mounts by itself, hence no `mountall`.

**Comment by samvde** [comment]
That was my initial understanding but then a mountall replacement is needed for ZoL. Are there any plans to replace this functionality or details how this will be deployed on Ubuntu starting from Vivid (with systemd)?

**Comment by dajhorn** [comment]
Given that systemd and ZoL are now both fully imported to Ubuntu main, I will close this ticket.

**Comment by weitzj** [comment]
Mountall still relies on upstart even in the released Ubuntu 16.04.
To actually mount additional volumes during boot you have to rely on `set mountpoint=legacy` and `/etc/fstab`
