### ISSUE TITLE
Allow specifying ZFS_DKMS_DISABLE_STRIP=y before installation.

### ISSUE THREAD

**Issue by tomprince** [zfsonlinux/pkg-zfs#133]
It is currently possible to do this non-interactively, after a bit of searching:

```
echo ZFS_DKMS_DISABLE_STRIP=y >> /etc/default/zfs
sudo env DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install -y zfsutils
```

but it would be nice if there was a more obvious way to do it. (This applies to spl too).

**Comment by FransUrbo** [comment]
Using <code>/etc/default/zfs</code> IS the correct way to do it…

Unless you can come up with a better, smarter, faster way to do it, I'm closing this for now.

The variables in that file is **environment** variables and sourced fairly early on, anything one would type or use in a command line or the shells environment would be overruled by that file. There is already a stanza in there for this variable, but it's set to "no" by default. Change the file (either by editing it or echo a new value in there as you did).
