### ISSUE TITLE
Fix or avoid launchpad/bzr git import errors caused by git submodules

### ISSUE THREAD

**Issue by krichter722** [zfsonlinux/pkg-zfs#134]
The import of the `zfs` git HEAD into the launchpad daily PPA at https://code.launchpad.net/~zfs-native/daily/zfs-linux/ currently fails (details at http://launchpadlibrarian.net/181619839/zfs-native-daily-zfs-linux.log) because of the incapacity of `bzr` to import git submodules[1], concretely the `zfs-images` submodule. `bzr` hasn't seen a lot of development since 2012[2] and neither has its `bzr-git` plugin. How to proceed? Either 
1. provide a git submodule-free clone of `zfs` (currently no big issue because `zfs-images` isn't involved in the build process and might even be a separate project) (= obeying `bzr`'s incapacities). I tried that myself, but it seems that I can't request an import for the empty PPA https://launchpad.net/~krichter722/+archive/ubuntu/zfs-linux-no-submodules, so I gave up (= fix) or
2. provide generic DKMS deb packages (currently RPM DKMS packages can't be installed with `alien -c -i` due to missing `chkconfig` and (missing links to) `insserv`, I might address that in a separate issue). If launchpad doesn't care about integrating git-based projects (maybe because it wants to push `bzr`) - the list on https://dev.launchpad.net/FailingBzrGitImports is long... - the packages could be build somewhere and binary, i.e. deb, packages uploaded into lauchpad without bothering with `bzr` import failures. (= avoid)

This would finally provide something that comes very close to a real daily PPA. The current daily PPA has the same status like the stable PPA for weeks now.

---

[1] https://bugs.launchpad.net/bzr-git/+bug/402814
[2] https://launchpad.net/bzr

**Comment by dajhorn** [comment]
This issue was eventually resolved by a downstream migration from bzr to git, and main import of ZoL, so I will close this ticket.

The old bzr recipes should be disabled and deleted when somebody next goes through that area of Launchpad.
