### ISSUE TITLE
zfsutils error: unable to read zfs.target

### ISSUE THREAD

**Issue by azeemism** [zfsonlinux/pkg-zfs#138]
Hi,

Regarding the dailies version of zfs:  0.6.3-22~2d9d57~jessie

When installing zfsutils (0.6.3-22~2d9d57~jessie) to a VirtualBox instance of Debian Jessie, I receive the following error (repeated twice):

/usr/bin/deb-systemd-helper: error: unable to read zfs.target

I am not sure if this is okay to ignore. Only related info I found was at these two links:

http://www.mattzone.com/zfsonlinux/zfsonlinux_20141015.html
https://groups.google.com/a/zfsonlinux.org/forum/#!topic/zfs-discuss/NdjlJBEqc10

init-system-helpers version installed is 1.22.

Not sure it this is related, but I also find that with a dailies install, /usr/lib/systemd/system/ is created with the following files:

zfs.target
zfs-share.service
zfs-mount.service
zfs-import-scan.service
zfs-import-cache service
zed.service

Thanks for all that you do,

Azeem

**Comment by azeemism** [comment]
I should also mention that when the non-dailies version of zfs is installed (v0.6.3-766_gfde0d6d), the following services do not exist on the system:

zfs.target
zfs-import-scan.service
zfs-import-cache service

And  zfs-mount.service and zfs-share.service are located in different places

find / -name zfs-*.service

/run/systemd/generator.late/
/run/systemd/generator.late/runlevel5.target.wants/
/sys/fs/cgroup/systemd/system.slice/

**Comment by FransUrbo** [comment]
Where is <code>zfs.target</code> supposed to go if not in <code>/usr/lib/systemd/system</code>?

**Comment by FransUrbo** [comment]
@azeemism I just created a new version for jessie-daily. If that also give the problem with <code>can't find zfs.target</code>, could you try moving all zfs/zed files from <code>/usr/lib/systemd/system</code> to <code>/lib/systemd/system</code> and try again?

If the later works, let me know and I'll move them in the package to...

**Comment by azeemism** [comment]
@FransUrbo Unfortunately installing the new dailies (0.6.3-23~6466b6~jessie) did not fix the issue.

However, your suggestion to moving the files was successful

from: /usr/lib/systemd/system 
to: /lib/systemd/system

/usr/lib/systemd/system only has zfs/zed files 

mv /usr/lib/systemd/system/\* /lib/systemd/system/
apt-get install --reinstall zfsutils

Now the install processed as follows without any errors:

...
setting up zfsutils (0.6.3-23~6466b6~jessie)
processing triggers for initramfs-tools (0.116)
update-initramfs: Generating /boot/initrd.img-3.16.0-4-amd64

I really appreciate your support.

Can I close this issue?

**Comment by FransUrbo** [comment]
> However, your suggestion to moving the files was successful
> 
> from: /usr/lib/systemd/system 
> to: /lib/systemd/system
> 
> Awesome! I'll create a new package with them there instead then. Thanx for testing!
> /usr/lib/systemd/system only has zfs/zed files
> 
> Yes, that's also 'mine' (from the ZoL packages). I'll move that as well then.
> Can I close this issue?
> 
> Sure. It's not technically fixed, but it will be in a couple of hours once I've uploaded the new packages...=

**Comment by azeemism** [comment]
Excellent! It's good to work with a nice team. 
...1 down, will now have another look at getting efi to work.
