### ISSUE TITLE
Pin-Priority of 1001 for ZoL breaks Debian security updates

### ISSUE THREAD

**Issue by AceSlash** [zfsonlinux/pkg-zfs#143]
The fact that the ZoL repository contains libc6 version 2.13-38+deb7u6 and that the Pin-Priority is higher for the ZoL repository than the Debian security repository prevent security updates from working normally:

```
# apt-cache policy libc6
libc6:
  Installed: 2.13-38+deb7u7
  Candidate: 2.13-38+deb7u6
  Version table:
     2.13-38+deb7u8 0
        990 http://security.debian.org/ wheezy/updates/main amd64 Packages
 *** 2.13-38+deb7u7 0
        100 /var/lib/dpkg/status
     2.13-38+deb7u6 0
        990 http://ftp.fr.debian.org/debian/ wheezy/main amd64 Packages
       1001 http://archive.zfsonlinux.org/debian/ wheezy-daily/main amd64 Packages
```

When you have dependencies (for example libc6-dev depends on libc6 2.13-38+deb7u8), the problem expends to them... removing the file "/etc/apt/preferences.d/pin-zfsonlinux" fixes the issue.

Is the higher pin-priority necessary? Without it, everything seems to work just fine.

**Comment by FransUrbo** [comment]
This was fixed in <code>zfsonlinux</code, version <code>5</code> (where the pin file was removed from the package and if it's found in the filesystem, removed from there as well).

Pinning is a bad idea, and bad things WILL happened...

**Comment by AceSlash** [comment]
May I suggest an update of the http://zfsonlinux.org/debian.html page, where zfsonlinux_4_all.deb is still referenced (as well as the pin file)?

**Comment by FransUrbo** [comment]
> May I suggest an update of the http://zfsonlinux.org/debian.html page, where zfsonlinux_4_all.deb is still referenced (as well as the pin file)?
> 
> Finally got time to do this. See https://github.com/zfsonlinux/zfsonlinux.github.com/pull/23.
