### ISSUE TITLE
[wish] add support for defining altroot somewhere in rc

### ISSUE THREAD

**Issue by h-2** [zfsonlinux/pkg-zfs#149]
I currently dual-boot Debian and FreeBSD. Debian boots from a ~~UFS disk~~  ext4 partition, but shares the ZFS with FreeBSD. Unfortunately this results in FreeBSD's /usr/ports being mounted to /usr/ports on Debian a.s.o. Luckily it doesnt mount over root or anything critical, but it's still not clean. And I always

``` sh
zfs umount -a
zpool export zroot
zpool import -f -R /zroot zroot
```

I would be really cool, if I could define a list somewhere that POOLX shall always be imported with alroot YZ. Would this be possible?

PS: I am not using systemd and don't plan to...

**Comment by FransUrbo** [comment]
> I would be really cool, if I could define a list somewhere that POOLX shall always be imported with alroot YZ. Would this be possible?
> 
> I'm not quite following.

You boot both FreeBSD and Debian GNU/Linux from the same pool with their respective root filesystem on ZFS?

**Comment by h-2** [comment]
No, I boot the Debian from ~~UFS~~ ext4, but I use the zpool from FreeBSD to excahnge and share data. Being able to boot from the same pool would be even cooler, but that's not necessary right now (and quite hard to do, unless grub could change the properties on the pool before booting I guess).

**Comment by FransUrbo** [comment]
I'm closing this as "stale". There is very little need for this, but if someone can come up with a clean patch, I'll take a look at it.
