### ISSUE TITLE
Ubuntu Snappy Integration

### ISSUE THREAD

**Issue by dajhorn** [zfsonlinux/pkg-zfs#155]
This ticket is for bucketing the initial work of fitting ZoL into the new Ubuntu `.snap` subsystem.

Ubuntu 16.04 LTS, tentatively the X series, née Ubuntu _NEXT_, will promote [Snappy](https://developer.ubuntu.com/en/snappy/) to a first-class platform component and deprecate corresponding parts of the Debian system in the Ubuntu Core distribution.

**Comment by chadmiller** [comment]
I think zfs will have to be a system-level package, which I'm pretty sure means dpkg. No change.

**Comment by dajhorn** [comment]
@chadmiller,

Right, and it became apparent that the actual issue for ZoL is that Snappy lacks PPA or other third-party repository support.  (ie: Snappy is a semi-closed platform in this regard.)

However, this concern is mooted by Ubuntu importing ZoL into regular distribution, so I will close this ticket.
