### ISSUE TITLE
create ZoL udeb packages for the Debian installer

### ISSUE THREAD

**Issue by dajhorn** [zfsonlinux/pkg-zfs#16]
Create ZoL ports of these Debian kFreeBSD packages:
- http://packages.debian.org/sid/libuutil1-udeb
- http://packages.debian.org/sid/libnvpair1-udeb
- http://packages.debian.org/sid/libzpool1-udeb
- http://packages.debian.org/sid/libzfs1-udeb
- http://packages.debian.org/sid/zfsutils-udeb
- http://packages.debian.org/sid/partman-zfs

**Comment by FransUrbo** [comment]
This is available in the <code>master/debian/wheezy/0.6.2*</code> tags and forward.
