### ISSUE TITLE
Ubuntu 14.04 zfs on root, bug with apt-get, remount tmp

### ISSUE THREAD

**Issue by alex-morgun** [zfsonlinux/pkg-zfs#165]
Not zfs bug, but needs workaround. apt somehow thinks that /tmp is a mount and tries to remount it.
I don't want to use tmpfs. Considering loop file based partition on zfs. What's your ideas?

root@x:/tmp# apt-get install htop
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  htop
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/68.0 kB of archives.
After this operation, 188 kB of additional disk space will be used.
mount: /tmp not mounted or bad option
E: Problem executing scripts DPkg::Pre-Invoke 'mount -o remount,exec /tmp'
E: Sub-process returned an error code

Mounts:
rpool/ROOT/production on / type zfs (rw,relatime,xattr,noacl)

**Comment by dajhorn** [comment]
Several things in Ubuntu give `/tmp` special handling.  This particular kind of glitch suggests that the root dataset is actually read-only or has some non-default permissions on it.

If `/tmp` is glitching inside a ZFS root, then create a dataset for it.

And vice-versa, if `/tmp` is mounted on a ZFS dataset, then move it elsewhere.

**Comment by dajhorn** [comment]
This is a known problem in Ubuntu releases before the systemd transition, and this particular ticket is stale, so I will close.  Feel free to comment further or reopen if something unique about it becomes apparent.
