### ISSUE TITLE
Debian pool import fails.

### ISSUE THREAD

**Issue by roedie** [zfsonlinux/pkg-zfs#166]
Hi,

After upgrading the Debian ZoL packages to 0.6.5 on wheezy my pool won't import with the error 'sort not found'.

It seems that /usr is not mounted at the point the import script is run. And since sort is in /usr/bin it is not available yet.

Removing the sort on line 584 in /etc/zfs/zfs-functions fixes it. Not sure why it needs to be sorted.

Sander

**Comment by FransUrbo** [comment]
It's not _needed_, but it's pretty :).

Removed in phase two of my init/initrd update (#3559).

**Comment by FransUrbo** [comment]
I believe this is fixed in latest debs.
