### ISSUE TITLE
Synchronize package with 0.6.5.1

### ISSUE THREAD

**Issue by rfc1459** [zfsonlinux/pkg-zfs#171]
As packaged right now, zfs-linux 0.6.5-2 only imports one of the three (more or less) urgent patches introduced with 0.6.5.1 - namely, the fix for TRIM leading to data corruption zfsonlinux/zfs#3798.

The package should be updated to include at the very least the patch for zfsonlinux/zfs#3804, which makes ZFS usable again as a storage driver for Docker.

**Comment by FransUrbo** [comment]
<code>0.6.5.1-2</code> have been out for almost twenty four hours...

**Comment by rfc1459** [comment]
Then I suppose that somebody forgot to upload the updated packages to the Ubuntu PPAs - not even the daily builds PPA has anything beyond 0.6.5-2.

**Comment by FransUrbo** [comment]
Ah, you might have lead with that :).

Reopening and tagging ubuntu.

**Comment by dajhorn** [comment]
The PPA already has the urgent patch, and the next point release will be built tonight.

**Comment by rfc1459** [comment]
@dajhorn: great, thanks and sorry for the whole fuss!
@FransUrbo: yeah, I kinda opened the issue in a hurry and forgot to say that I was talking about Ubuntu. Sorry :-)

**Comment by FransUrbo** [comment]
@dajhorn Is this still an issue?

**Comment by dajhorn** [comment]
@FransUrbo, no, closing.
