### ISSUE TITLE
read config from /etc/default/zfs

### ISSUE THREAD

**Issue by ggzengel** [zfsonlinux/pkg-zfs#173]
# cat zfs-import-scan.service | grep ExecStart=

ExecStart=/sbin/zpool import -d /dev/disk/by-id -aN

**Comment by FransUrbo** [comment]
See https://github.com/zfsonlinux/zfs/pull/3884

**Comment by FransUrbo** [comment]
Not really relevant to the pkg-zfs repo. Closing.
