### ISSUE TITLE
Debian: How to install specific version of zfs?

### ISSUE THREAD

**Issue by xuanngo2001** [zfsonlinux/pkg-zfs#174]
Debian: How to install specific version of zfs?
I don't want to always get the latest version from the repository.
Is it possible to keep at least the previous version for a certain time(month?) instead of purging old version when new version is out. New version might not be stable or new behavior is not desired.
Installing from source is not practical.

**Comment by FransUrbo** [comment]
Original issue: zfsonlinux/zfs#3843

**Comment by ghost** [comment]
Unrelated to ZFS, and doesn't really help you get earlier versions, but if you install cron-apt https://packages.debian.org/stable/cron-apt and leave it configured only for downloading, you can copy the files out of /var/cache/apt/archives. You can then trivially set up a cron job or even a post-download script in /etc/cron-apt/action.d to copy the .debs to a stable location where they will be available for future reference and use. It shouldn't be too hard to write a script to delete old versions after a while. All paths mentioned here assuming no special configuration.

**Comment by FransUrbo** [comment]
I'm now keeping old versions, so I'm closing this.
