### ISSUE TITLE
Hangs on mounting root pool

### ISSUE THREAD

**Issue by Ryushin** [zfsonlinux/pkg-zfs#175]
Just rebooted after upgrading to 0.6.5.1.  Running Debian Wheezy.  Packages version 0.6.5.1-4-wheezy.

When mounting the rpool it hangs with "...".  Typing exit or using ctrl+d allows it to continue.  Screenshot from my IPMI:
http://postimg.org/image/l8gsgk2md/

My rpool zfs list:
rpool                                269G   267G  25.4K  none
rpool/ROOT                           269G   267G  4.21G  /
rpool/ROOT/var                       249G   267G  8.34G  /var
rpool/ROOT/var/lib                   180G   267G   318M  /var/lib
rpool/ROOT/var/lib/mysql            9.89G   267G  5.92G  /var/lib/mysql
rpool/ROOT/var/lib/plexmediaserver   160G   267G   155G  /var/lib/plexmediaserver
rpool/ROOT/var/oi_db_backups        46.1G   267G  46.1G  /var/oi_db_backups
rpool/ROOT/var/spool                12.4G   267G  10.4G  /var/spool

I'm using the newest /etc/default/zfs and the only option I changed is  DO_OVERLAY_MOUNTS='yes'.  I did also just turn on VERBOSE_MOUNT='yes' but that did not seem to provide any other information.

My grub linux boot line looks like this:
linux   /vmlinuz-3.16.0-0.bpo.4-amd64 root=ZFS=rpool/ROOT ro boot=zfs $bootfs usb-storage.delay_use=5

**Comment by FransUrbo** [comment]
Sorry, there's a regression. I've accidentally changed <code>DO_OVERLAY_MOUNTS</code> to <code>OVERLAY_MOUNTS</code> in the code :(.

We're working on a fix, but you you add that second define _as well_ (don't remove the DO_… part, it will work again in the next version), you can try again.

**Comment by FransUrbo** [comment]
If neither of this works or changes anything, you can manually add a <code>zfsdebug=1</code> on the grub kernel command line at next boot.

**Comment by Ryushin** [comment]
I'll be able to test this again in a couple of days.  Thanks for getting back with me.

**Comment by Ryushin** [comment]
The latest update 0.6.5.2-2-wheezy seems to have fixed the issue.  Thank you for spending the time looking at this.
