### ISSUE TITLE
reflect debian wheezy -> jessie update in version numbers

### ISSUE THREAD

**Issue by woffs** [zfsonlinux/pkg-zfs#176]
the Wheezy (Debian 7) packages have version 0.6.5.1-4-wheezy, the Jessie (Debian 8) packages have version 0.6.5.1-4 without suffix. When upgrading from Wheezy to Jessie the Wheezy version numbers are higher than the Jessie version numbers, but they should be lower. I suggest using ~wheezy instead of -wheezy or using the Debian release number instead of the name (for J is less then W).

**Comment by FransUrbo** [comment]
There is. The Wheezy versions are suffixed with <code>wheezy</code>. Unfortunately, for technical reasons, it's almost impossible to accommodate ALL types of upgrades and the Wheezy to Jessie was one that couldn't happen :(

**Comment by woffs** [comment]
you are faster in replying than me in writing the issue ;-)

**Comment by FransUrbo** [comment]
:). Thanx, I try to please :D. But you where just lucky, I was already online checking my GitHub messages and fixing some PRs of mine...
