### ISSUE TITLE
zed init script is not installed on 0.6.5.x on ubuntu

### ISSUE THREAD

**Issue by mailinglists35** [zfsonlinux/pkg-zfs#185]
I have no /etc/init.d/zed after upgrading from 0.6.4 to 0.6.5.x
neither on debian jessie/wheezy nor on ubuntu precise
ubuntu precise 0.6.5.3 also lacks /etc/zfs/zed.d completely!

**Comment by FransUrbo** [comment]
In the Debian GNU/Linux package, this is named <code>/etc/init.d/zfs-zed</code>.

**Comment by FransUrbo** [comment]
@dajhorn Is this still a problem in ubuntu?

**Comment by dajhorn** [comment]
@FransUrbo, this is a `wontfix` on Precise and is mooted on current releases by the MIR integration work.  Therefore closing.
