### ISSUE TITLE
Removing old kernels makes dkms build spl+zfs before removing the modules and kernel

### ISSUE THREAD

**Issue by dasjoe** [zfsonlinux/pkg-zfs#187]
Apparently dkms keeps modules built and installed for just a few (last 2?) kernel versions, older kernel's modules get removed even though the kernel package doesn't.

This causes dkms to build the spl and zfs modules when removing odler kernels, just to remove them once it built them.

Building ZFS on my N54L takes around 8 minutes, so I've been watching DKMS rebuild the modules for an hour or so by now.

**Comment by dasjoe** [comment]
Running `/etc/kernel/postinst.d/dkms` is the culprit, I'm not sure whether this issue is in pkg-zfs or upstream dkms.

```
Removing linux-image-extra-3.13.0-44-generic (3.13.0-44.73) ...
run-parts: executing /etc/kernel/postinst.d/apt-auto-removal 3.13.0-44-generic /boot/vmlinuz-3.13.0-44-generic
run-parts: executing /etc/kernel/postinst.d/dkms 3.13.0-44-generic /boot/vmlinuz-3.13.0-44-generic
run-parts: executing /etc/kernel/postinst.d/initramfs-tools 3.13.0-44-generic /boot/vmlinuz-3.13.0-44-generic
update-initramfs: Generating /boot/initrd.img-3.13.0-44-generic
run-parts: executing /etc/kernel/postinst.d/update-notifier 3.13.0-44-generic /boot/vmlinuz-3.13.0-44-generic
run-parts: executing /etc/kernel/postinst.d/zz-update-grub 3.13.0-44-generic /boot/vmlinuz-3.13.0-44-generic
Generating grub configuration file ...
```

**Comment by FransUrbo** [comment]
I'm fairly certain this is a problem with **dkms**, which sucks. But it's what we got :(

**Comment by dajhorn** [comment]
Three factors here:
- Distro integration of ZoL moots this issue.  (eg: Ubuntu 16.04 LTS bundling ZFS modules; hopefully Debian and most other distributions soon.)
- This behavior is a design choice that is favored both upstream and downstream.  Patches that change it are unlikely to be accepted, even though there are good reasons to have a fix.
- Changing this behavior in a side-loaded package would be a non-trivial amount of work and carry a large testing burden.  (zfsonlinux/pkg-zfs#12 would have a similar solution.)

I will, therefore, close this ticket as a `wontfix` in this repository.
