### ISSUE TITLE
installing ZFS using the LiveCD on Xenial?

### ISSUE THREAD

**Issue by devekko** [zfsonlinux/pkg-zfs#188]
excuse my ignorance, I am trying for the ZFS root Ubuntu install from a USB drive with the Xenial Desktop LiveCD ISO

but when I drop into command line while in the LiveCD for Xenial after adding the Universe sources on bare-metal I am able to open a terminal and run 

 $ sudo apt-get install zfsutils-linux zfs-initramfs zfs-dkms  
$ sudo modprobe zfs

but the install stalls as this is a LiveCD and it wont let me install the zfs module etc

no doubt I am missing something obvious

how do I drop into shell from the "disk" screen in Ubiquity? 

thanks

**Comment by kernelOfTruth** [comment]
Please ask on the zfsonlinux IRC channel on freenode or a forum with knowledgeable users that also went to install ZFS root for Ubuntu, or at least open an entry at https://github.com/zfsonlinux/zfs/issues

this issue tracker is for: "Native ZFS packaging for Debian and Ubuntu"

so not really related/suited for your issue

**Comment by devekko** [comment]
no problem

I posted here because of this wiki page
https://github.com/zfsonlinux/pkg-zfs/wiki/HOWTO-install-Ubuntu-16.04-to-a-Native-ZFS-Root-Filesystem

THANKS

**Comment by kernelOfTruth** [comment]
@devekko

Alright, leave it here, then

I'm sure the maintainers, owners will complain if it doesn't fit in here ;)

 please note that it clearly says:

"in progress"

so some parts might be missing yet,

you could, however, ask the authors of the wiki, who can be found,

when pushing the "Edit" button and then on "Page History"

under "Revisions"

To answer your question.

usually the install should involve a step where you update the initramfs,

which seems to be missing in the guide (or it's done automagically ?) by quickly glancing over it

anyway:

compare the wiki entry against:

http://linoxide.com/ubuntu-how-to/configure-ubuntu-14-04-to-a-native-zfs-root-filesystem/

https://www.reddit.com/r/zfs/comments/3qinlh/native_zfs_root_on_ubuntu_1510/

and a little asking on IRC might get you to your goal of having a working installation

grub might however be a hurdle, so keep lilo in mind as an alternative

**Comment by dajhorn** [comment]
Please try the Xenial dailies:
- http://cdimage.ubuntu.com/ubuntu/daily-live/current/

This ticket, which was closed today, suggests that Ubuntu 16.04 LTS could ship with ZoL binaries:
- https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1509881

**Comment by devekko** [comment]
hi, again

thanks for all this

I am testing on a lab box with the desktop edition of the xenial dailies and looking in ubiquity for zfs option, its not there

however, thats fine, pretty sure I can install the OS the standard way and then drop into shell etc and install zfs for the formerly raid drives only. ... its not a root install, but, less complicated for me I think

trying to remember where I saw the ZFS option screenshot in ubiquity... somewhere on a blog

**Comment by aidabeorn** [comment]
What I've found from testing:
You have to enable universe repo in /etc/apt/sources.list and install the tools.

Ubiquity does not recognize ZFS an installable partition type, so best approach for now is probably to install and migrate over.

**Comment by devekko** [comment]
thanks for the update

**Comment by kmatt** [comment]
> Ubiquity does not recognize ZFS an installable partition type

Should this be a GH issue here, or elsewhere? An issue search on this project did not show anything open or closed.

**Comment by devekko** [comment]
do you want me to make an issue on Launchpad?

**Comment by kmatt** [comment]
@devekko If that gets it on the development radar, please! Bootable ZFS on root would be a great feature, as with FreeBSD 10.

**Comment by dajhorn** [comment]
This feature was deferred downstream in the Ubuntu 16.06 LTS release, I will close this ticket.

It follows that anybody wanting improved root-in-ZFS support should report issues against the Yakkety dailies and put the `metoo` flag on tickets at Launchpad.

**Comment by kmatt** [comment]
@dajhorn Is that deferred downstream in the Ubuntu **16.04** LTS release ? In other words support for ZFS in the installer is not currently targeted in a specific release?

**Comment by dajhorn** [comment]
@kmatt, this feature doesn't appear in any public roadmap document for Ubuntu.

Note that manually installing to a ZFS root is still possible.  (@rlaager is updating tutorial documentation in various places.)

**Comment by rlaager** [comment]
@kmatt https://github.com/rlaager/zfs/wiki/Ubuntu-16.04-Root-on-ZFS
