### ISSUE TITLE
ZFS pool features for whole-disk mirror rpool (/) if /boot is on external drive

### ISSUE THREAD

**Issue by osinskit** [zfsonlinux/pkg-zfs#191]
I installed system (ubuntu 16.04) in such way:
- /boot is on external drive
- /boot/efi is on the same drive as /boot
- / is on mirrored ZFS (whole disks, not partitions)

There will be a large pool added later (most probably 2xraidz2 pool with l2arc)
Installation was based on (and the pool was created with the features recommended by):
https://github.com/zfsonlinux/pkg-zfs/wiki/HOWTO-install-Ubuntu-16.04-to-a-Native-ZFS-Root-Filesystem
A small modification was that I put /boot and /boot/efi on external drive and created whole disk mirror for /

My question is:
Can I enable all features available for current ZFS pool version (zpool upgrade mymirroredpool) or doing it will make the system unbootable from grub (again: /boot and /boot/efi are on separate disk, / is a whole-disk mirror pool)?

I do not have the possibility to test it myself, so if anybody did something similar I will be grateful

**Comment by dajhorn** [comment]
@osinskit, GRUB support will always lag ZoL, so using the latest ZFS features could indeed make the system unbootable.  Unless you have a specific need for a new feature flag, then I recommend following the documentation for root pools.

**Comment by osinskit** [comment]
Great! Thanks for the answer.

**Comment by dajhorn** [comment]
@osinskit, welcome.
