### ISSUE TITLE
[Feature Request] Add additional files (such as service and init files etc) for Debian (Jessie) into the ZoL GIT releases

### ISSUE THREAD

**Issue by azeemism** [zfsonlinux/pkg-zfs#197]
@behlendorf there is great work done by the ZoL team. For the end users who appreciate the output and want to stay current with each **Official** ZoL releases, it would be extremely helpful if KMOD packages can be build from the tarballs created from the GIT tags (possibly even DKMS packages as a further second alternative).

At current they may be some bandage solutions but these these will always be less effective than what @FransUrbo efforts yield in creating **Genuine** .deb's built the correct, Debian GNU/Linux, way. Building genuine .deb's looks to be a very involved process, and that puts a lot of pressure on a package maintainer. Automating this process and giving the end user more control over creating .deb packages would serve several purposes:
1. Ease the pressure on the Debian package maintainer and the additional resources needed for hosting or a build environment
2. Allow Debian users who appreciate ZoL (and they are lots of us) a chance to stay current with ZoL release within their current distro version
3. Be timely.

Yes, Debian has indicate support to carry ZoL, but there is no time frame, no certainty on "zfs-linux" being uploaded. If they are still some legal issues outstanding, at what point would it become reasonable to produce genuine .deb's?
https://qa.debian.org/developer.php?login=pkg-zfsonlinux-devel@lists.alioth.debian.org

In the very least, I hope that genuine .deb's can be created for at least the official ZoL releases until both spl-linux and zfs-linux can be pulled from testing/unstable. @FransUrbo I hope this is feasible. 

Reference:
#181

**Comment by FransUrbo** [comment]
> it would be extremely helpful if KMOD packages can be build from the tarballs created from the GIT tags (possibly even DKMS packages as a further second alternative).
> 
> Yeah, I've been trying to lobby for this for quite some time. I even created a PR for this, but there have been absolutly no interest in even discussing this!

Personally, it really pisses me of that we have RPM spec files for almost every RPM based dist, but not the debian directory to build native DEBs!

> Building genuine .deb's looks to be a very involved process
> 
> It really isn't. "debuild" is easier to use than "rpmbuild" :). And better documented! :D
> Yes, Debian has indicate support to carry ZoL, but there is no time frame, no certainty on "zfs-linux" being uploaded.
> 
> And there (probably) won't be much support for those that want to run bleeding edge. Yes, in "Unstable", we'll probably do packages every now and then (and I've been playing with Jenkins which is a code deploy tool) at work and I find it very interesting to setup something like that to push debs for every git commit in ZoL!

We'll see what happens with that once it's been accepted.

> If they are still some legal issues outstanding, at what point would it become reasonable to produce genuine .deb's?
> 
> Not to our knowledge.
> In the very least, I hope that genuine .deb's can be created for at least the official ZoL releases until both spl-linux and zfs-linux can be pulled from testing/unstable. @FransUrbo I hope this is feasible.
> 
> As I've said, I'll at least do one more release as soon as all my cables arrive (last week was last I heard, but they're still haven't arrived). We'll see what happens after that.

**Comment by doctorjames** [comment]
@FransUrbo In the interim is it worth keeping the debian directory in a separate git repository that can be cloned/untarred into a ZoL source directory?

**Comment by FransUrbo** [comment]
> @FransUrbo In the interim is it worth keeping the debian directory in a separate git repository that can be cloned/untarred into a ZoL source directory?
> 
> To much work to do that now. But checkout the correct tag and extract the dir yourself...

**Comment by FransUrbo** [comment]
This is not going to happen. See zfsonlinux/zfs#1713
