### ISSUE TITLE
Install seemingly superficial error on Ubuntu 11.04

### ISSUE THREAD

**Issue by dajhorn** [zfsonlinux/pkg-zfs#2]
Hi,

1st thanks for all your hard work truly appreciate it!!

I upgraded zfs through the ppa on Ubuntu 11.04 and it gave me this error. Seems to be superficial since it still installs and works but I'm not sure.

Loading new zfs-0.6.0.17 DKMS files...
Building only for 2.6.38-8-server
Building initial module for 2.6.38-8-server
config.status: error: cannot find input file: scripts/Makefile.in
Done.

Thought you'd like to know.

—Mike

**Comment by markab** [comment]
Hi,

Yes I get the same on the current version for 11.04.

Thanks,
Mark

ureadahead will be reprofiled on next reboot
Setting up zfs-dkms (0.6.0.20-0ubuntu1~natty1) ...
Loading new zfs-0.6.0.20 DKMS files...
Building only for 2.6.38-8-server
Building initial module for 2.6.38-8-server
config.status: error: cannot find input file: scripts/Makefile.in
Done.

**Comment by Nowaker** [comment]
Same here.
