### ISSUE TITLE
ZFS not accessible after rebooting

### ISSUE THREAD

**Issue by pnorton** [zfsonlinux/pkg-zfs#20]
First, let me say that I am new to Linux and this might just be a series of failed skill checks on my part.

This is probably the third maybe fourth fresh install Turnkey Linux's FileServer (http://www.turnkeylinux.org/fileserver) followed by a install of ZFS.

The PPA did not seem to work for me I ended up with the same issues as https://github.com/dajhorn/pkg-zfs/issues/6 but the official instructions referenced by Zodling only let to more errors

For my last attempt I tried a combination of the install instructions from the following..
http://www.howtoforge.com/native-zfs-on-ubuntu
http://zfsonlinux.org/spl-building-deb.html
http://zfsonlinux.org/zfs-building-deb.html

I performed the following:

--Build system
Clean install
setup network
pull system updates

--grab prereqs
apt-get install build-essential gawk zlib1g-dev uuid-dev
apt-get install build-essential gawk alien fakeroot linux-headers-$(uname -r)     ( I know it overlaps)
cd /usr/src

--Build and install SPL
wget http://github.com/downloads/zfsonlinux/spl/spl-0.5.2.tar.gz
tar -xvzf spl-0.5.2.tar.gz
cd spl-0.5.2
./configure  (no errors)
make    (no errors)
make install  (no errors)

--Build and install ZFS
wget http://github.com/downloads/zfsonlinux/zfs/zfs-0.5.2.tar.gz
tar -xvzf zfs-0.5.2.tar.gz
cp zfs-0.5.2
./configure  (no errors)
make    (no errors)
make install  (no errors)

--Check installation
modprobe splat
splat -a
modprobe zfs
lsmod |grep zfs

it all looked good to me.....

ran zfs and zpool received the following error
zfs: error while loading shared libraries: libspl.so.0: cannot open shared object file: No such file or directory 
So I executed: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

then ran a zpool import to import a single disk pool.  No errors
ZFS did not mount the vol.  I was not able to use legacy mounting or manually mounting it.  I receive no errors when I unmounted then mounted it again.  So I decided to reboot thinking that maybe zfs needed a clean startup.

Upon rebooting, I received the error for cannot open shared object file... so I followed (http://www.cyberciti.biz/faq/set-environment-variable-linux/) to make the change permanent then rebooted.  

Upon rebooting I no longer have a colored terminal (putty) (no big deal to me but I'd like to fix it) and now I receive the following errors. 

root@fileserver:/# zfs import
Failed to load ZFS module stack.
Load the module manually by running 'insmod <location>/zfs.ko' as root.
root@fileserver:/# modprobe splat
FATAL: Could not load /lib/modules/2.6.32-37-generic/modules.dep: No such file or directory
root@fileserver:/# modprobe zfs
FATAL: Could not load /lib/modules/2.6.32-37-generic/modules.dep: No such file or directory

Now, yes, I fundamentally get and understand that the files are missing..... but why did it work just fine the first time before I rebooted?  Sure, maybe the installation process loaded everything thus skipping these checks.

So returning to (https://github.com/dajhorn/pkg-zfs/issues/6#issuecomment-1590302).. I decided to run

root@fileserver:/# dkms status
-bash: dkms: command not found

After installing it...
root@fileserver:/# dkms status
root@fileserver:/#

If you would not mind pointing me in the right direction that would be awesome.  I'm kinda lost on this.  Thanks

**Comment by dajhorn** [comment]
The howtoforge instructions and software are obsolete and not intended for the pkg-zfs builds.  I will close this ticket because the 0.5.2 release is unsupported and was removed from the PPA a long time ago.

If you really want to use the 0.5.2 release, then you must also install the lzfs package from KQ Infotech.

Note that the PPA is incompatible with a local ZoL installation, like you would get by using the `make install` command in any way.  You must completely clean the system, which can be difficult, or start fresh.

Please open a new issue if you have a problem with a package that you installed from the ZoL PPA.  Send an email to zfs-discuss@zfsonlinux.org if you have a question or need advice.

**Comment by dajhorn** [comment]
What is the output of these commands?

```
# uname -a
# dkms status
# find /lib/modules -name zfs.ko
```
