### ISSUE TITLE
pkg-spl debian/jessie 0.6.5.6-1 and 0.6.5.6-2 based on debian/jessie 0.6.5.4-1b packaging instead of 0.6.5-1 packaging?

### ISSUE THREAD

**Issue by Fabian-Gruenbichler** [zfsonlinux/pkg-zfs#204]
See the end of #181 for background, posting as new issue like @FransUrbo suggested. (the pkg-spl repo only allows PRs).

The pkg-spl jessie releases 0.6.5.6-1 and 0.6.5.6-2 have dropped a lot of packaging changes contained in the jessie 0.6.5-1 release, reverting to a debian/ dir like the 0.6.4 release. The wheezy 0.6.5.6 package (only available in the archive.zfsonlinux.org package repository, and not pushed to pkg-spl on github!) does not revert to 0.6.4's packaging, but is based on 0.6.5-1's debian/ directory. The pkg-zfs releases (both jessie and wheezy) also do not revert to 0.6.4.

Since this means that 3 out of 4 packages do one thing, and 1 does something completely different (and seemingly backwards?), I'd like to get confirmation from the maintainers that this change to pkg-spl's jessie packaging files was actually intentional, and not the result of a merge gone wrong ;)

The following changelog entries from 0.6.4-1b..0.6.5-1 were silently dropped, the second and last seem relevant regarding changes to the debian/ directory which are now no longer included in the package's current release:

```
spl-linux (0.6.5-1) jessie; urgency=low

  * New upstream release

 -- Turbo Fredriksson <turbo@debian.org>  Thu, 17 Sep 2015 13:36:22 +0200

spl-linux (0.6.4-8-8ac6ff) jessie; urgency=low

  * Package zfs-modules-source needs to conflict and replace zfs-dkms
    and vise versa.
  * New upstream GIT version.

 -- Turbo Fredriksson <turbo@debian.org>  Tue, 18 Aug 2015 12:29:48 +0200

spl-linux (0.6.4-7-4699d7) jessie; urgency=low

  * New upstream GIT version.

 -- Turbo Fredriksson <turbo@debian.org>  Mon, 27 Jul 2015 17:54:47 +0200

spl-linux (0.6.4-6-37d7cd) jessie; urgency=low

  * New upstream GIT version.

 -- Turbo Fredriksson <turbo@debian.org>  Sat, 18 Jul 2015 18:11:26 +0200

spl-linux (0.6.4-5-3c8216) jessie; urgency=low

  * New upstream GIT version.

 -- Turbo Fredriksson <turbo@debian.org>  Fri, 26 Jun 2015 00:43:30 +0200

spl-linux (0.6.4-4-234536) jessie; urgency=low

  * New upstream GIT version.

 -- Turbo Fredriksson <turbo@debian.org>  Thu, 11 Jun 2015 20:38:58 +0200

spl-linux (0.6.4-3-a876b0) jessie; urgency=low

  * New upstream GIT version.

 -- Turbo Fredriksson <turbo@debian.org>  Thu, 11 Jun 2015 09:54:06 +0200

spl-linux (0.6.4-2-62e2eb) jessie; urgency=low

  * New upstream GIT version.
    + Remove module package stuff.

 -- Turbo Fredriksson <turbo@debian.org>  Tue, 12 May 2015 14:18:13 +0200
```

Thanks in advance for looking into this!

P.s. 0.6.5.6-2 only fixed the errors in debian/gbp.conf that were a result of this "revert", but did not touch anything else like the way the modules are built..

**Comment by FransUrbo** [comment]
Fixed in the new <code>0.6.5.6-3</code> package which is now uploading to the repository.
