### ISSUE TITLE
Ubuntu 16.04 Native ZFS Root Guide

### ISSUE THREAD

**Issue by ukjbrown** [zfsonlinux/pkg-zfs#208]
This guide seems to need re-visiting. I'm not sure if it ever worked for the BETA, but it doesn't seem to work for the final LTS release. You just end up with an unbootable system if you follow these steps. The steps don't seem to go as far as the 14.04 guide, which did seem to work. I'm going to attempt to follow the 14.04 guide for 16.04 to see if that works instead, as it is much more detailed.

Also, I fell at the first hurdle with this guide as a "fresh installer", as it states the following;

> In the fresh install path, you will start the installer, get to the point you are asked to prepare your disks, and hop out to a shell to get things ready.

What exactly does this mean? Hop out to a shell? The only shell I could hop out to at this stage is the BusyBox shell available in the Ubuntu installer. This certainly doesn't give you access to the tools you need to install the ZFS tools and partition the disks. Am I misunderstanding?

As such, I had to continue with installation to ext4 and then follow the guide as if I were migrating. It would therefore seem better to just create a LiveUSB/CD and do it that way.

The lack of an out-the-box install option for ZFS in 16.04 is disappointing considering all the hype around it. I'm surprised there doesn't seem to be a clear, working guide published by Ubuntu (or anyone else for that matter) as yet.

**Comment by zidarko** [comment]
> What exactly does this mean? Hop out to a shell? The only shell I could hop out to at this stage is the BusyBox shell available in the Ubuntu installer.

He's probably refering to the terminal that you can start if you boot a Live Ubuntu USB/DVD.

> The lack of an out-the-box install option for ZFS in 16.04 is disappointing considering all the hype around it. I'm surprised there doesn't seem to be a clear, working guide published by Ubuntu (or anyone else for that matter) as yet.

Ubuntu says ZFS is not meant to be used by "mere mortals". I agree with your disappointment.

**Comment by FransUrbo** [comment]
I'm closing this. The HOWTO is a Wiki, feel free to modify it.
