### ISSUE TITLE
[nightlies, jessie] zfs-dkms will not work without newer commit from spl

### ISSUE THREAD

**Issue by DHowett** [zfsonlinux/pkg-zfs#211]
zfs-dkms is currently at zfs@b7faa7a, but in zfs@9baaa7deae45c8556dfd79b2011234da5cb37b3a (before zfs@b7faa7a) a dependency on spl@fdbc1ba99d1f4d3958189079eee9b6c957e0264b was introduced. spl-dkms is, unfortunately, at spl@39cd90e (which predates the `inode_lock` fixes.)

**Comment by FransUrbo** [comment]
Sorry, and thanx for the heads up! My autobuilder have been having trouble auto-building stuff on commits the last couple of weeks.

I'll start a build of newer spl right away. Should be in the repo in a few hours.

**Comment by D4rk4** [comment]
Can you rebuild pkg and deploy it to repo?

**Comment by FransUrbo** [comment]
> Can you rebuild pkg and deploy it to repo?
> 
> Working on it.

**Comment by FransUrbo** [comment]
@DHowett Is this fixed?

**Comment by DHowett** [comment]
Yep, it looks like zfs-dkms now builds.
