### ISSUE TITLE
No ZFS 0.6.5.8 in debian repo

### ISSUE THREAD

**Issue by D4rk4** [zfsonlinux/pkg-zfs#213]
No new 'stable' version of ZFS and SPL in official repo - http://archive.zfsonlinux.org/debian

**Comment by 0xFelix** [comment]
Same for me.

**Comment by behlendorf** [comment]
The official Debian packages are now maintained by Debian - https://tracker.debian.org/pkg/zfs-linux.  The repo archive.zfsonlinux.org repository will remain available until the end of the year but won't be updated with new packages.
