### ISSUE TITLE
Ubuntu-zfs stable packages out of date

### ISSUE THREAD

**Issue by gdevenyi** [zfsonlinux/pkg-zfs#217]
Stable seems to be stuck on 0.6.5.7, although it seems daily is still getting updated.

**Comment by behlendorf** [comment]
Updated official packages are now being provided by Debian.  Users are encouraged to transition away from the archive.zfsonlinux.org repositories which will eventually be retired.

https://tracker.debian.org/pkg/zfs-linux

**Comment by gdevenyi** [comment]
Will the install instructions be updated to indicate this?

**Comment by behlendorf** [comment]
Yes, take a look at https://github.com/zfsonlinux/zfs/wiki/Debian

**Comment by gdevenyi** [comment]
Sorry to follow up again, this all seems to be for debian, will there be any updated packages for Ubuntu (12, 14)?
