### ISSUE TITLE
zfs-grub has dependency issue in zfs-native/stable

### ISSUE THREAD

**Issue by icculus** [zfsonlinux/pkg-zfs#22]
When following the instructions at...

```
https://github.com/dajhorn/pkg-zfs/wiki/HOWTO-install-Ubuntu-to-a-Native-ZFS-Root-Filesystem
```

...when we get to the point where we run this in the chroot...

```
apt-get install ubuntu-zfs zfs-initramfs
```

...it fails with this output...

```
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
  zfs-initramfs : Depends: zfs-grub
E: Unable to correct problems, you have held broken packages.
```

...if we try to do zfs-grub instead, we get this...

```
apt-get install zfs-grub

Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'grub-common' instead of 'zfs-grub'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
  grub-common : Depends: libzfs1 (>= 0.6.0.47) but it is not going to be installed
            Recommends: os-prober (>= 1.33) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

...please note that this problem does not exist in the /daily packages at the moment, but it's breaking the stable packages, which means you need to use the bleeding edge to get set up in the first place.

--ryan.

(EDIT: markdown cleanup.)

**Comment by dajhorn** [comment]
I put ppa:zfs-native/daliy in the tutorial to make it accurate. Thanks for the report.

This happened because I'm tracking the Ubuntu 11.10 backports and the Ubuntu 12.04 LTS alpha releases.  The stable PPA is incompatible with the Linux 3.1 and Linux 3.2 kernel packages that most people are using, and the latest GRUB releases are also problematic.

I don't intent to update ppa:zfs-native/grub for Lucid, Maverick, or Natty except for security notices.  If you are using Oneiric and want to stay on the RC, then you must manually install the Natty packages instead.

**Comment by wkearney99** [comment]
This problem persists in 12.10 following your ZFS install instructions.

(It would help if instructions included steps for Quantal)

**Comment by dajhorn** [comment]
@wkearney99   I didn't publish for Ubuntu 12.10 Quantal.  The last supported release is Precise.
