### ISSUE TITLE
PPA packages for xenial / yakkety

### ISSUE THREAD

**Issue by nilsmeyer** [zfsonlinux/pkg-zfs#220]
Since upstream is upgraded rather infrequently (or not at all) it would be great if the PPA also provided packages for xenial and yakkety.

**Comment by dajhorn** [comment]
@nilsmeyer, the PPA is deprecated and will eventually be delisted.  There was, unfortunately, minimal interest in maintaining the PPA after the upstream import.

**Comment by nilsmeyer** [comment]
Fair enough, I thought that perhaps the tooling to do that automatically was still in place. I've managed so far to build packages of my own for my private repo, perhaps I can set up a ppa at some point.
