### ISSUE TITLE
implement `beadm` for Linux

### ISSUE THREAD

**Issue by dajhorn** [zfsonlinux/pkg-zfs#24]
Solaris provides a `beadm` utility for managing system snapshots in the `tank/ROOT/` hierarchy.  Linux would benefit from having a similar facility.

Automatically hook package managers like `apt` and `yum` too.

**Comment by clopez** [comment]
Here is the code from Illumos for the beadm utility: https://github.com/illumos/illumos-gate/tree/master/usr/src/cmd/beadm

And here is the code for libbe: https://github.com/illumos/illumos-gate/tree/master/usr/src/lib/libbe

**Comment by FransUrbo** [comment]
If booting from a snapshot is the intention, then this is now possible in the Debian GNU/Linux Wheezy snapshot tags.

**Comment by FransUrbo** [comment]
I'm closing this as stale, and the fact that it really don't belong to the packaging.

**Comment by yangm97** [comment]
Is it being discussed elsewhere? If so would be interesting to have it liked here, this literally the first google result for “beadm linux”.

**Comment by au-phiware** [comment]
@yangm97 You may be interested in [b333z/beadm](https://github.com/b333z/beadm) which is discussed here: http://list.zfsonlinux.org/pipermail/zfs-discuss/2014-December/020009.html
