### ISSUE TITLE
Boot from ZFS Wiki - boot from mirror or raidz?

### ISSUE THREAD

**Issue by pyavdr** [zfsonlinux/pkg-zfs#34]
@dajhorn

Hi Darik,

reading through your Wiki for booting from ZFS with Ubuntu, im missing a hint on how to create a boot device consisting of multiple vdevs ( e.g. mirror or raidz), as it would be common practice on servers to put a boot environment to at least a Raid1 vdev. 

Is there a chance to add such configuration to your wiki? Or is it not possible to boot from such a configuration?

Thanks!

**Comment by dajhorn** [comment]
Booting from a mirror is already supported.  Just create a mirrored vdev at Step 3.2 and optionally mirror the loader and /boot area in the usual way.  Attaching a second disk to an existing ZoL root pool should work as expected.

I will add a note about this when I next update the tutorial.

GRUB 2 could have RAIDZ support, but a steady stream of bugs is being reported against the beta release on the support lists, so it isn't obvious whether GRUB 2 will be ready for the Quantal release series.

**Comment by pyavdr** [comment]
Im working through that tutorial with a vmware guest session, trying as a newbie. 
using /dev/disk/by-path because by-id is mostly empty within vmware workstation.

Some questions:
4.4 should it be debootstrap precise /mnt   ... according to point 0) .. just for consistency if we want to install precise?
5.5 locale... this maybe critical .... my main language is german i use de_DE.UTF-8 but im in doubt if this is correct 
5.7 if ubuntu-desktop is installed at this point, it fails at point 7.2 "mount /mnt/dev  + zfs umount -a " with device busy
6.3 the grub.cfg file contains a second line with "boot=zfs" .... should be in the tutorial 

on reboot with zfs i got several errors from grub :
wrong fs typ or bad superblock or  bad option or missing codepage ....
error : mountall mount /boot/grub terminated with status 32, Filesystem could not be mounted: /boot/grub 
but this message can be ignored with "S" for skip and it boots.

looking at the zpool status afterwards the main vdev is /dev/sda2 which should be /dev/disk/by-path ... it defaults somewhere to /dev/sda ...

need to create the /etc/default/locale file afterwards

got a new error on boot --- unknown mount option -0 ... 
changed the fstab entry to /dev/sda1 /boot/grub
error on boot changed to :  rpool no yet ready yet but booted without more problems

**Comment by dajhorn** [comment]
> Im working through that tutorial with a vmware guest session, trying as a newbie. using /dev/disk/by-path because by-id is mostly empty within vmware workstation.

This is a VMware bug.

> 4.4 should it be debootstrap precise /mnt ... according to point 0) .. just for consistency if we want to install precise?

Yes.

> 5.5 locale... this maybe critical .... my main language is german i use de_DE.UTF-8 but im in doubt if this is correct

Always do English for the default C locale to avoid frustration. Optionally do de_DE.UTF-8 or any other language.

> 5.7 if ubuntu-desktop is installed at this point, it fails at point 7.2 "mount /mnt/dev + zfs umount -a " with device busy

The ubuntu-desktop package started one or more daemons in the chroot that needs to be stopped.  Run `lsof /mnt` and kill those processes so that `/mnt` can be dismounted.

> 6.3 the grub.cfg file contains a second line with "boot=zfs" .... should be in the tutorial

Okay.

**Comment by pyavdr** [comment]
I would like to say thank you for that tutorial. This is great work.

My intention is to check and test if ZOL is reliable in future for business usage.
I dont want to be pedantic or so, just checking if  this tutorial works. 
Pls consider my points as hints for improvement of this tutorial from a users perspective and as 
help for you to see where a user may fail.
Not all zol users have detailed knowledge of grub and bootstrap configurations, so they may fail on peanuts.

For Vmware Workstation it is possible to include "disk.EnableUUID = "TRUE" " in the vmx file. Sometimes the /dev/disk/by-id is filled then after a reboot. The same can be done on ESX (http://www.novell.com/support/kb/doc.php?id=7002966)
Maybe there should be a hint for Vmware users to use /dev/sd\* instead of /dev/disk/by-id, though it may lead to failures.

It would be really great if you can add the detailed steps for zfs only configurations with mirrored vdevs.
Next: it would be nice to pack all this commands in a script (with some input parameters), it takes me 4 hours to go through 4 times.

Thank you!

**Comment by dajhorn** [comment]
> For Vmware Workstation it is possible to include "disk.EnableUUID = "TRUE" " in the vmx file. Sometimes the /dev/disk/by-id is filled then after a reboot. The same can be done on ESX (http://www.novell.com/support/kb/doc.php?id=7002966)

Thanks for point this out.  Most VMware users have this problem.

**Comment by pdf** [comment]
Same goes for QEMU/KVM - users should explicitly set a serial on their disks.  Additionally for KVM, `/etc/default/grub` should have the `GRUB_TERMINAL=console` line uncommented, and `splash` removed from `GRUB_CMDLINE_LINUX_DEFAULT` or boot errors may occur.

I'd also suggest moving the option to install `ubuntu-desktop` to some post-install instructions so that umount errors can be avoided.

**Comment by dajhorn** [comment]
Okay, good idea.

**Comment by dajhorn** [comment]
Closed by https://github.com/dajhorn/pkg-zfs/wiki/HOWTO-install-Ubuntu-to-a-Native-ZFS-Root-Filesystem/83d566c4e4654b24bcf2cf81a6c72ae8d096d720
