### ISSUE TITLE
Migrate zfs-share to upstart on Ubuntu

### ISSUE THREAD

**Issue by pdf** [zfsonlinux/pkg-zfs#47]
Primary motivation for me on this is better dependency control, in particular I'd like `start on starting libvirt-bin` as I have VMs that depend on NFS shares exported by the host (I could do this via Upstart  overrides, rather than modifying the installed init conf).  Happy to provide a patch if it would be considered.

As for zfs-mount, I'm not even sure that should be included on Ubuntu since we use mountall, so it only provides for confusion.

**Comment by dajhorn** [comment]
This is status quo because the same code is currently built for both of Debian and Ubuntu. I am intending to do these things when I branch for Wheezy. (dajhorn/pkg-zfs#46)

If you submit a patch, then I will quickly add it to the Quantal builds.

**Comment by pdf** [comment]
Yeah, I assumed as much.  Was concerned it might be more overhead than it's worth, but if the split's going to be desirable/required anyway, all good.  I'll shoot through a patch in the next couple of days.  Should I base it on master or the quantal branch?

**Comment by pdf** [comment]
This is harder than expected, due to the current state of NFS packaging in Ubuntu.  Nearly all NFS-related daemons are now handled by Upstart, but nfs-kernel-server is not, and there are no events emitted by SysV scripts (just another Upstart design flaw), so an Upstart job can't depend on nfs-kernel-server.  There's also [this bug](https://bugs.launchpad.net/ubuntu/+source/nfs-utils/+bug/1052264) that will impact the current script.

**Comment by dajhorn** [comment]
I'm adding the 'upstream' tag to this ticket because it will be difficult to properly implement with side-loaded packages.

**Comment by pdf** [comment]
Yeah, NFS init in Ubuntu is still a mess.  There may be a way to make this work for NFS by watching for an nfsd mount event, but because share also handles SMB (and iSCSI eventually), that's probably not adequate.

**Comment by dajhorn** [comment]
I'm closing this ticket because upstart is now deprecated in Ubuntu per:
- http://www.markshuttleworth.com/archives/1316

Any effort here would be better put into integrating the systemd parts that came with commit zfsonlinux/zfs@881f45c6a8f44486f76c4713ecef0d533d6601e8 in the pending ZoL 0.6.3 release.
