### ISSUE TITLE
ubuntu native zfs install instructions

### ISSUE THREAD

**Issue by Phoenixxl** [zfsonlinux/pkg-zfs#51]
Using the 12.04.1 live cd. with these instructions:
https://github.com/dajhorn/pkg-zfs/wiki/HOWTO-install-Ubuntu-to-a-Native-ZFS-Root-Filesystem

part 1.2

yesterday , while, daily was at .79:
 apt-get install debootstrap ubuntu-zfs 

failed on the zfs part , saying zfs could not determine the spl version.

What did work yesterday was doing an install of spl-dkms manually then an install zfs-dkms , then ubuntu-zfs over that.

Today when at .80 , doing the install zfs-dkms it fails saying it's not able to determine zpl version as well. 

So installation using those instructions is broken starting today.

---

not related and not asking for any help on this, I haven't been able to get a system to boot yet. everything in the instructions installs and seems to work fine up until the moment one has to reboot. I tried making grub stay on longer thinking i may have mieed it , but alas no grub to be seen. The system goes past post , reads a bit of the ssd then i see the lights flash on all hdd's , then the screen stays black. numlock still works. 
I'm trying to figure out what the issue could be. Today I will do the whole install again but with /stable instead of /daily. I will go scavenge for a 12.04 cd as well instead of a 12.04.1 .
I was wondering if a .56 was available on ppa so I have everything at the same version of when the install instructions were made. 
I am thinking the issue is grub related though...
step 5/6 seems to rely on grub-pc  : http://i.imgur.com/6l46b.png
while troubleshooting seems to rely on zfs-grub from ppa:zfs-native/grub : http://i.imgur.com/Na93W.png
I am assuming grub-pc  is a newer patched version and the troubleshooting part is a paste from older instructions?

---

Thnx in advance for any reply .

**Comment by dajhorn** [comment]
> failed on the zfs part , saying zfs could not determine the spl version.

I need the full error message or and build transcript to help you.  This is probably a transient error where zfs-dkms is built before spl-dkms.

> not related and not asking for any help on this, I haven't been able to get a system to boot yet.

Hold down the left <shift> button during POST to get the GRUB prompt and diagnostic information.  (Ubuntu hides it by default.)

> I am assuming grub-pc is a newer patched version and the troubleshooting part is a paste from older instructions?

No, the phrasing is intentional.  It produces a different error message that lets me identify people that do not follow instructions.  Many people try to skip steps or improve the procedure and then complain that the documentation doesn't work.

**Comment by Phoenixxl** [comment]
Well after trying a few more times for .80 at point 1.2 : "apt-get install ubuntu-zfs" works again without giving the spl version error ( without needing to install spl-dkms and zfs-dkms ) like what happened in .79 so all is fine. I hadn't tried it .
For the second part , after the last reboot I left the thing on and went and grabbed a coffee , had a chat , then came back , lo and behold , I had a prompt !
So rebooting again and looking at my watch while doing so , It took grub 7 minutes to show up!
So I checked if a new bios was out for that particular MB , flashed to the latest , problem gone.
I knew it was something fishy , that's why i said there was no need to go into it tbh.

**Comment by dajhorn** [comment]
What is the manufacturer and model of the motherboard?  What BIOS revision fixed the problem?

**Comment by Phoenixxl** [comment]
http://www.asrock.com/mb/overview.asp?Model=ALiveNF7G-HD720p%20R5.0

going from 2.10 to 2.20 fixed it.

**Comment by Phoenixxl** [comment]
Ok , continuing this feedback on instructions thread , I came across a few more things,

Also concerning what you mentioned here : https://github.com/dajhorn/pkg-zfs/issues/48

After getting the thing to boot on a stick , I went and bought an ssd , and instead of installing /boot/grub on partition 1 , I made it a tad bigger to make it hold /boot . This is the only way I was able to get it to have root be a raidz . I do get some errors when grub starts , but it boots anyway. something about it not finding an valid label .. (I'll add a some pictures) . I had tried before trying to get it to use /boot/grub only on the ssd , but that never worked . I had a different error every install , which was related to reading junk data from the wrong place imo but idk, first one was about not finding a magic number , second about being unable to decompress ,( I have some pics of that too , ill add them. for good measure) they all had the "kernel needs to be loaded first" bit in common.

Anyway , now with /boot on a 400 mb partition on the ssd , and using the rest as l2arc I am able to use 3 sata drives in raidZ . (the error about not finding an label that pops up at boot comes from the line zfs-boot ($root) bootfs)

The main issue I find worth adding to this thread is this: 

Unlike my other machines with zpools which are only data I figured I needed to do some extra testing . 
So I firstly removed a drive when cold then booted up , in that case I only had to online the drive when inserted again.
Secondly I removed a drive while live after offlining it , then inserted and onlined it again which worked fine.
Thirdly I just yanked one drive out , while writing some data , then stuck it back in. I onlined it , it was ok too. even did a scrub to check , all was fine.

But , when I did an offline , remove drive , stick in a replacement drive , then do a replace I get this :

zpool replace rpool /dev/disk/by-path/pci-0000:00:09.0-scsi-3:0:0:0
cannot label 'sdd': EFI labeled devices are not supported on root pools.

things I tried:
I dd'd some empty blocks at the start of it.. 
I made a gpt myself..
made an msdos partition table.
partitionned it exactly like the one it's supposed to replace.
used  bsd, dvh, gpt, mac, msdos, pc98, sun, loop types as label.

same error each time.

The nearest thing to a solution that comes to mind is:
 load a live cd
 install zfs in live environment
 then (as a hunch)
   removing the bootfs property on rpool
   renaming the pool 
then try to replace the drive , hoping it won't be seen as a root pool ...
  renaming it again
  setting the property again.
exporting the pool..
reboot .

If this is the case , it really should be added to the documentation for running a root pool on linux.

The other thing I could try is , instead of making it out of disks , making the pool out of partitions instead.. I'd rather not do that tbh , but if it's the only way to make it work well..

I'm sure there is a way to do this that works , and I'm just overlooking it .

Related:
 For my current install to be able to use raidz , I followed the same instructions but substituted /boot/grub by /boot .
Are there extra things I should change when installing this way?

Also , a few things I found noteworthy feedback while following this install procedure ( about two dozen times _grinn_ - i'l llive , it's all added knowledge ) :

Parted has no BE nor BF settings , nor Solaris or Solaris boot.

After doing a mk2fs the boot/grub partition is marked as ext3 , no longer BE i figured it wasn't that important , but in the beginning while my system wouldn't boot , I spent some time investigating if that could be the cause

grep boot=zfs /boot/grub/grub.cfg contains 2 lines not 1 , I wasn't too worried , since i knew it was recovery mode , but people who don't use linux all that much might start fiddling with the generated cfg.

---

when trying to install on a raidz with /boot/grub on the ssd this is what happened.
I tried with ashift set to 12 , without , with cache , without , from a 12.04 cd from a 12.04.1 cd using daily , using stable , and most combinations of those. as i mentioned earlier , the errors were all different , even with identical installs.. probably from trying to interpret junk data .
I don't expect these to have any meaning , but I added them for good measure.
here are a few:
http://i.imgur.com/SMYPY.jpg
http://i.imgur.com/CrCtW.jpg
http://i.imgur.com/DGR9F.jpg

On my now booting system , I get this while booting:
http://i.imgur.com/s8cDg.png
the next reboot i got :
http://i.imgur.com/bWgJm.jpg
When I boot , and force the grub screen to show I always get :
http://i.imgur.com/T65Iq.jpg

So the first one is a tad funky , sometimes it's 2 errors sometimes it's 1 , just like when I tried to use only /boot/grub. They change from time to time , but seem to have no impact.
The second seems to be grub cosmetics .
the last comes from the "zfs-boot ($root) bootfs" line in grub. When i comment that one out , the system starts just the same , but without giving that error.

PS: It's logical that i can't export my rpool , but If I import it forcefully by booting from another install , then export it again , will it give issues? I was thinking of installing an ubuntu minimal + zfs on a usb drive for recovery purposes.

Thnx in advance for any reply . My biggest concern is replacing a drive in a root pool which is raidz. 

Regards Phoenixxl.

**Comment by dajhorn** [comment]
> the error about not finding an label that pops up at boot comes from the line zfs-boot ($root) bootfs

This is a known problem that is related to dajhorn/pkg-zfs#27.

> zpool replace rpool /dev/disk/by-path/pci-0000:00:09.0-scsi-3:0:0:0
> cannot label 'sdd': EFI labeled devices are not supported on root pools.
> ...
> If this is the case , it really should be added to the documentation for running a root pool on linux.

This is indeed the case; it is a restriction inherited from Solaris that is still appropriate for ZoL.

> For my current install to be able to use raidz , I followed the same instructions but substituted /boot/grub by /boot .
> Are there extra things I should change when installing this way?

I don't remember.

> http://i.imgur.com/SMYPY.jpg
> 
> ```
> error: file not found.
> error: you need to load the kernel first.
> 
> Press any key to continue...
> ```

Per bug #27, the `grub.cfg` file is incorrectly generated if boot and root are on separate devices. You must set something like `boot=zfs rpool=tank bootfs=tank/ROOT/ubuntu-1` in the `/etc/default/grub` file.

This problem will resolve when the GRUB `search` directive reliably recognizes ZoL UUIDs.

> http://i.imgur.com/CrCtW.jpg
> 
> ```
> error: lzjb decompression failed.
> error: you need to load the kernel first.
> 
> Press any key to continue...
> ```

GRUB cannot load a kernel or initrd from a compressed dataset.  This is described in the Troubleshooting section of the documentation.

> http://i.imgur.com/DGR9F.jpg
> 
> ```
> error: unknown ZAP type.
> error: you need to load the kernel first.
> 
> Press any key to continue...
> ```

Scrub the pool. This can also happen if you install GRUB for Linux on a pool that was created by Solaris or Illumos.

> ```
> On my now booting system , I get this while booting:
> http://i.imgur.com/s8cDg.png
> the next reboot i got :
> http://i.imgur.com/bWgJm.jpg
> When I boot , and force the grub screen to show I always get :
> http://i.imgur.com/T65Iq.jpg
> ```

Scrub the pool, run `grub-probe -vvv` on the boot device, and look for checksum errors in the ZFS detection routine.

> PS: It's logical that i can't export my rpool , but If I import it forcefully by booting from another install , then export it again , will it give issues? I was thinking of installing an ubuntu minimal + zfs on a usb drive for recovery purposes.

Ensure that the `/etc/zfs/zpool.cache` is current in the regular system and in the initrd.  Running `update-initramfs` copies the `/etc/zfs/zpool.cache` from the system into the initrd.

**Comment by Phoenixxl** [comment]
> > zpool replace rpool /dev/disk/by-path/pci-0000:00:09.0-scsi-3:0:0:0
> > cannot label 'sdd': EFI labeled devices are not supported on root pools.
> > ...
> > I>>f this is the case , it really should be added to the documentation for running a root pool on linux.
> 
> This is indeed the case; it is a restriction inherited from Solaris that is still appropriate for ZoL.

So when I need to replace a drive , what would you recommend ? 
I presume , when importing the pool on a rescue system , replacing it there , then exporting again will alter /etc/zfs/zpool.cache .. ? Or will it be identical since the info concerning the drives used is by path instead of by-id?

> Ensure that the /etc/zfs/zpool.cache is current in the regular system and in the initrd. Running update-initramfs copies the /etc/zfs/zpool.cache from the system into the initrd.

So copying the zpool.cache from the rescue system to the live one , and manually adding it to initrd...

**Comment by dajhorn** [comment]
> So when I need to replace a drive , what would you recommend ? 

Put a single large MBR partition on the new disk before using it to replace the old disk.

ZoL doesn't really use raw disks; it just creates an EFI partition table on a blank disk by default.

> I presume , when importing the pool on a rescue system , replacing it there , then exporting again will alter /etc/zfs/zpool.cache .. ? Or will it be identical since the info concerning the drives used is by path instead of by-id?

You must force-import the pool on the regular system after touching it in a rescue environment.  Don't assume any behavior regarding the `zpool.cache` file between any two system instances.

**Comment by Phoenixxl** [comment]
> ZoL doesn't really use raw disks; it just creates an EFI partition table on a blank disk by default.

So basically , if I partition manually , then use the /dev/disk/by-path/pci-0000:00:09.0-scsi-3:0:0:0-part1 instead of the whole disk when creating the pool I can later replace it with another partition. 

Ok I'll try that then. 

Thnx.

## 

The thing is I want everything to work by-path , without needing to mess with ID's and brand names . 

Doing a :
zpool replace rpool /dev/disk/by-path/pci-0000:00:09.0-scsi-3:0:0:0-part1

should still not matter which brand of drive with which ID is in the slot , as long as it has a partition .. Am I correctly assuming this ? Replacing with a partition that's exactly the same or larger should be ok?
  Somehow in the back of my mind I worry about performance issues ie I have an image of using straight sectors instead of a disk image on file lurking in the back of my mind. But using whole disks or using partitions has nothing to do with this , it's basically the same. 
Also , ease of use , but having to make a partition before doing a replace won't kill me , I'll just stick a post it to the front of the case :)

I am also making sure I start my partitions at 2048s and making sure they are a multiple of that in size for the sake of good alignment.

Thank you again for all the fast replies.

## 

ps : those errors mentioned here :

> here are a few:
> http://i.imgur.com/SMYPY.jpg
> http://i.imgur.com/CrCtW.jpg
> http://i.imgur.com/DGR9F.jpg

Are all from trying to install using /boot/grub together with raidZ on separate drives . zol isn't supposed to be able to do that right? when those installs booted , and I edited the location of the kernel , grub said it wasn't able to locate it.. so I assume the zfs equal of a "file allocation table" is still valid , it's just the data that is being read that's faulty ? I never compressed anything , it just assumes something is compressed due to reading garbage data which happens to have the same header?

**Comment by dajhorn** [comment]
> Am I correctly assuming this ? Replacing with a partition that's exactly the same or larger should be ok?

Yes.

> Somehow in the back of my mind I worry about performance issues ie I have an image of using straight sectors instead of a disk image on file lurking in the back of my mind. But using whole disks or using partitions has nothing to do with this , it's basically the same. 

The partition should be aligned to a sector boundary for optimal performance.  Modern utilities like `parted` will do this automatically, usually an even multiple of 512 and 4096 near one megabyte.  Older utilities like the classic `fdisk` do not.

> I am also making sure I start my partitions at 2048s and making sure they are a multiple of that in size for the sake of good alignment.

Right.

> Thank you again for all the fast replies.

Welcome.

> Are all from trying to install using /boot/grub together with raidZ on separate drives . zol isn't supposed to be able to do that right? when those installs booted , and I edited the location of the kernel , grub said it wasn't able to locate it.. so I assume the zfs equal of a "file allocation table" is still valid , it's just the data that is being read that's faulty ? I never compressed anything , it just assumes something is compressed due to reading garbage data which happens to have the same header?

This is a latent bug in the GRUB code that we have been unable to diagnose. Sometimes it works, and sometimes it doesn't. YMMV.

Right now, booting from a single or mirrored vdev is the only reliable configuration.

**Comment by dajhorn** [comment]
The daily PPA has some updates that could mitigate these problems:
- A dkms package with basic module dependency support.
- Commit c372b36e3eba18d1a8747b8375e3e7c049d40c89.

Past that, grub doesn't have any recent improvements for booting from raidz pools.  Please open a new ticket if this problem persists for single pools or mirrored pools.

**Comment by dajhorn** [comment]
> can one safely do a "zpool upgrade" on a system running zfs natively ..
> ie with the OS installed on the disk which has to be upgraded?

No, the GRUB package for Ubuntu 12.04 Precise does not recognize feature
flags.  Upgrading beyond pool version 28 will break root installations that
use the PPA.

Only Ubuntu systems that use grub-1.99 are currently affected.  Most other
distributions are shipping a grub-2.00 package that recognizes recent zpool
revisions.
