### ISSUE TITLE
ubuntu server 12.04 FATAL: Module zfs not found.

### ISSUE THREAD

**Issue by leprechuan** [zfsonlinux/pkg-zfs#52]
Hi
I have been having a problem with getting zfs to work on my server.
If i try to mount a drive i get the following message: "Failed to load ZFS module stack.
Load the module manually by running 'insmod <location>/zfs.ko' as root."
Found in another thread that i should try modprobe zfs and that gives me the following error: "FATAL: Module zfs not found." i don't know what is wrong or what my next step should be any help is appreciated

**Comment by dajhorn** [comment]
How did you install ZoL?  What does the `dkms status` command return?  What versions of Debian or Ubuntu are you using?

**Comment by leprechuan** [comment]
i followed the folling guide to get it installed: http://www.danielscottlawrence.com/installing-zfs-on-ubuntu-server-12-04-running-on-a-n40l/
I am running ubuntu server 12.04 and dkms status returns:
  spl, 0.6.0.80: added
zfs, 0.6.0.80: added

**Comment by dajhorn** [comment]
Always do a full system upgrade after adding a PPA.  That document is missing this command:

```
# apt-get dist-upgrade
```

Also run these two commands to finish the installation:

```
# dkms install -m spl -v 0.6.0.80
# dkms install -m zfs -v 0.6.0.80
```

The PPA is only tested against official Ubuntu kernels. Note that:
- The `kpkg` utility must be used to install customized kernels.
- A 64-bit kernel is always required, even on something like the N40L.
- If you did anything but a regular default Ubuntu installation, then you must install the `build-essential` package and the appropriate `kernel-headers-*` package.

If the problem persists, then provide the full build transcript (do a CTRL-A copy in the terminal window) and the output of these commands:

```
# lsb_release -a
# uname -a
# dmesg : or the `/var/log/kern.log` file.
```
