### ISSUE TITLE
module build 3.5.0.18-generic fails after zfs-dkms build (zfs-0.6.0.80)

### ISSUE THREAD

**Issue by stephanvaningen** [zfsonlinux/pkg-zfs#56]
Got this in apt-get install output:
  :
  DKMS: install completed.
  Setting up zfs-dkms (0.6.0.80-1ubuntu1~quantal1) ...
  Loading new zfs-0.6.0.80 DKMS files...
  Building only for 3.5.0-18-generic
  Building initial module for 3.5.0-18-generic
  Error! Bad return status for module build on kernel: 3.5.0-18-generic (i686)
  Consult /var/lib/dkms/zfs/0.6.0.80/build/make.log for more information.
  Setting up zfsutils (0.6.0.80-1ubuntu1~quantal1) ...
  Processing triggers for initramfs-tools ...
  update-initramfs: Generating /boot/initrd.img-3.5.0-18-generic
  : 

This was a resulto f apt-get install --reinstall spl spl-dkms zfs-dkms zfsutils because previous build(s) also failed. History:
- First used Ubuntu 12.04 zith zfs-fuse
- Then removed zfs-fuse and installed ubuntu-zfs via ppa
- Then I could not mount my zpools anymore. thought to upgrade to Ubuntu 12.10
- Same result, then I un-installed zfs packages and re-install

Current situation is than when I do something like sudo zpool status I get message that I need to insmod the zfs.ko, which is nowhere to be found.
(I did make quite a mess of this, historically, but last steps were complete removal of zfs and complete re-install: with above result...?)

**Comment by dajhorn** [comment]
> Consult /var/lib/dkms/zfs/0.6.0.80/build/make.log for more information.

Please post this file to http://gist.github.com/ and link it to this ticket.

Double-check that the linux-headers-3.5.0-18-generic, linux-headers-generic, and build-essential packages are installed.

> Then I could not mount my zpools anymore. thought to upgrade to Ubuntu 12.10

Did you get an error message when this happened?

Remember that you need to force the import unless you remembered to run `zpool export` before uninstalling zfs-fuse.

> Current situation is than when I do something like sudo zpool status I get message that I need to insmod the zfs.ko, which is nowhere to be found.

This error message is inaccurate, which is a bug, so ignore it.

**Comment by stephanvaningen** [comment]
Darik, thanks for the info!
Since I already cleared the server image, I can not provide the above info, but because you gave the tip about required packages I did these two tests:

1/2
Installed clean ubuntu-12.10-desktop-amd64.iso (downlaoded 2012-11-06), then:
 apt-add-repository ppa:zfs-native/stable
 apt-get update
 apt-get install ubuntu-zfs
=> This resulted in "Failed to load ZFS module stack" when doing 'zpool status'
=> When installing the above mentioned required packages afterwards: errors on module-builds etc... so no resolution

2/2
Installed clean ubuntu-12.10-desktop-amd64.iso (downlaoded 2012-11-06), then:
 apt-get install linux-headers-3.5.0-18-generic linux-headers-generic build-essential
 apt-add-repository ppa:zfs-native/stable
 apt-get update
 apt-get install ubuntu-zfs
=> This resulted in the expected good end-result

==> Which brings me to the question why linux-headers-3.5.0-18-generic, linux-headers-generic and build-essential are not defined as required dependencies in the ubuntu-zfs package? Or am I overlooking something?

**Comment by dajhorn** [comment]
> Which brings me to the question why linux-headers-3.5.0-18-generic, linux-headers-generic and build-essential are not defined as required dependencies in the ubuntu-zfs package? Or am I overlooking something?

ZoL depends on these things indirectly through DKMS.

```
$ apt-cache depends zfs-dkms
zfs-dkms
  Depends: dkms
  Depends: spl-dkms
  Conflicts: <lzfs>
  Conflicts: <lzfs:i386>
  Conflicts: <lzfs-dkms>
  Conflicts: <lzfs-dkms:i386>
  Replaces: <lzfs>
    zfs-dkms
  Replaces: <lzfs:i386>
    zfs-dkms:i386
  Replaces: <lzfs-dkms>
    zfs-dkms
  Replaces: <lzfs-dkms:i386>
    zfs-dkms:i386
  Conflicts: zfs-dkms:i386

$ apt-cache depends dkms
dkms
  Depends: module-init-tools
    module-init-tools:i386
  Depends: gcc
 |Depends: make
 |Depends: build-essential
  Depends: dpkg-dev
  Depends: coreutils
    coreutils:i386
  Depends: patch
    patch:i386
  Recommends: fakeroot
 |Recommends: menu
  Recommends: sudo
    sudo-ldap
 |Recommends: <linux-headers-generic-pae>
 |Recommends: <linux-headers-686-pae>
 |Recommends: <linux-headers-amd64>
 |Recommends: linux-headers-generic
```

A default Ubuntu installation has the kernel headers.  Custom installations might not.  This is by design.

**Comment by stephanvaningen** [comment]
Ok, thanks for the info! I did have default installation, but it had headers 3.5.0-17-generic...

**Comment by dajhorn** [comment]
I'm glad that your problem is resolved. This can also happen if ZoL is installed before an Ubuntu installation is fully updated for the first time.
