### ISSUE TITLE
Ubuntu native ZFS root Grub Install Issue

### ISSUE THREAD

**Issue by treykyle** [zfsonlinux/pkg-zfs#57]
I have 2 16gb usb sticks in a mirrored pool, and am trying to install grub to the mbr on one of the sticks. I have followed the instructions, but am getting an error when doing the zfs-grub install. I am using the latest Ubuntu 12.04 x64 live cd.

Here is the output of troubleshooting commands:

root@ubuntu:/# apt-get install --reinstall zfs-grub
Reading package lists... Done
Building dependency tree  
Reading state information... Done
Note, selecting 'grub-common' instead of 'zfs-grub'
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 1 not upgraded.
2 not fully installed or removed.
Need to get 0 B/2,356 kB of archives.
After this operation, 0 B of additional disk space will be used.
Can not write log, openpty() failed (/dev/pts not mounted?)
(Reading database ... 43041 files and directories currently installed.)
Preparing to replace grub-common 1.99-21ubuntu3+zfs1 (using .../grub-common_1.99-21ubuntu3+zfs1_amd64.deb) ...
Unpacking replacement grub-common ...
Processing triggers for ureadahead ...
Can not write log, openpty() failed (/dev/pts not mounted?)
Setting up grub-common (1.99-21ubuntu3+zfs1) ...
Setting up grub-pc (1.99-21ubuntu3+zfs1) ...
grub-probe: error: cannot find a device for / (is /dev mounted?).
grub-probe: error: cannot find a device for /boot (is /dev mounted?).
Installation finished. No error reported.
/usr/sbin/grub-probe: error: cannot find a device for / (is /dev mounted?).
dpkg: error processing grub-pc (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of grub-gfxpayload-lists:
 grub-gfxpayload-lists depends on grub-pc (>= 1.99~20101210-1ubuntu2); however:
  Package grub-pc is not configured yet.
dpkg: error processing grub-gfxpayload-lists (--configure):
 dependency problems - leaving unconfigured
No apport report written because MaxReports is reached already
No apport report written because MaxReports is reached already
Errors were encountered while processing:
 grub-pc
 grub-gfxpayload-lists
E: Sub-process /usr/bin/dpkg returned an error code (1)

root@ubuntu:/# grub-probe /
grub-probe: error: cannot find a device for / (is /dev mounted?).
root@ubuntu:/# ls /boot/grub/zfs*
/boot/grub/zfsinfo.mod  /boot/grub/zfs.mod
root@ubuntu:/# update-initramfs -c -k all
update-initramfs: Generating /boot/initrd.img-3.2.0-23-generic
root@ubuntu:/# update-grub
/usr/sbin/grub-probe: error: cannot find a device for / (is /dev mounted?).
root@ubuntu:/# grep boot=zfs /boot/grub/grub.cfg
root@ubuntu:/# grub-install $(readlink -f /dev/disk/by-id/usb-PNY_USB_2.0_FD_00000000327AA39B-0:0)
Installation finished. No error reported.
root@ubuntu:/# ls /dev
autofs           network_latency     sde9      tty14  tty53      ttyS5
block            network_throughput  sdf       tty15  tty54      ttyS6
bsg              null                sdf1      tty16  tty55      ttyS7
btrfs-control    oldmem              sdf9      tty17  tty56      ttyS8
bus              port                sdg       tty18  tty57      ttyS9
cdrom            ppp                 sdg1      tty19  tty58      uinput
cdrw             psaux               sdg9      tty2   tty59      urandom
char             ptmx                sdh       tty20  tty6       usb
console          pts                 sdh1      tty21  tty60      usbmon0
core             ram0                sdh2      tty22  tty61      usbmon1
cpu              ram1                sdi       tty23  tty62      usbmon2
cpu_dma_latency  ram10               sdi1      tty24  tty63      usbmon3
disk             ram11               sdi2      tty25  tty7       usbmon4
dri              ram12               sdj       tty26  tty8       usbmon5
dvd              ram13               sdj1      tty27  tty9       usbmon6
dvdrw            ram14               sdj2      tty28  ttyprintk  usbmon7
ecryptfs         ram15               sdj3      tty29  ttyS0      usbmon8
fb0              ram2                sdj5      tty3   ttyS1      v4l
fd               ram3                sg0       tty30  ttyS10     vcs
full             ram4                sg1       tty31  ttyS11     vcs1
fuse             ram5                sg10      tty32  ttyS12     vcs2
fw0              ram6                sg2       tty33  ttyS13     vcs3
hidraw0          ram7                sg3       tty34  ttyS14     vcs4
hidraw1          ram8                sg4       tty35  ttyS15     vcs5
hidraw2          ram9                sg5       tty36  ttyS16     vcs6
hidraw3          random              sg6       tty37  ttyS17     vcs7
hpet             rfkill              sg7       tty38  ttyS18     vcsa
input            rtc                 sg8       tty39  ttyS19     vcsa1
kmsg             rtc0                sg9       tty4   ttyS2      vcsa2
log              sda                 shm       tty40  ttyS20     vcsa3
loop0            sda1                snapshot  tty41  ttyS21     vcsa4
loop1            sda9                snd       tty42  ttyS22     vcsa5
loop2            sdb                 sr0       tty43  ttyS23     vcsa6
loop3            sdb1                stderr    tty44  ttyS24     vcsa7
loop4            sdb9                stdin     tty45  ttyS25     vga_arbiter
loop5            sdc                 stdout    tty46  ttyS26     video0
loop6            sdc1                tty       tty47  ttyS27     zero
loop7            sdc9                tty0      tty48  ttyS28     zfs
loop-control     sdd                 tty1      tty49  ttyS29
mapper           sdd1                tty10     tty5   ttyS3
mcelog           sdd9                tty11     tty50  ttyS30
mem              sde                 tty12     tty51  ttyS31
net              sde1                tty13     tty52  ttyS4
root@ubuntu:/# ls /
bin   dev  home        lib    media  opt   root  sbin     srv  tmp  var
boot  etc  initrd.img  lib64  mnt    proc  run   selinux  sys  usr  vmlinuz

**Comment by dajhorn** [comment]
> I have 2 16gb usb sticks in a mirrored pool, and am trying to install grub to the mbr on one of the sticks. I have followed the instructions, but am getting an error when doing the zfs-grub install.

Whether this configuration is reliable depends on BIOS behavior. A single USB boot device is usually a better choice.

> dpkg: dependency problems prevent configuration of grub-gfxpayload-lists:
> grub-gfxpayload-lists depends on grub-pc (>= 1.99~20101210-1ubuntu2); however:
> Package grub-pc is not configured yet.

Something was installed out of order.  If you are working in a virtual machine, then it would be easiest to scratch and try again.  If not, then manually install the packages from here:

https://launchpad.net/~zfs-native/+archive/grub/+sourcepub/2387939/+listing-archive-extra

You need:
- grub-common
- grub-pc
- grub-pc-bin

Plus:
- grub-gfxpayload-lists from the regular Ubuntu archive.

A single `dpkg --install` command must be used to install `grub-pc` and `grub-gfxpayload-lists`.

**Comment by treykyle** [comment]
Just to clarify I set up a pool with the 2nd partition from each usb stick. In theory I should be able to install grub to the first partition of either stick and boot to it assuming I have that particular stick set to mount in fstab and configured in the bios to boot from.

**Comment by treykyle** [comment]
It is still giving me an error when trying to install the grub-pc manually. I will try a third time to start from scratch and see what happens.

dpkg -i grub-common_1.99-21ubuntu3+zfs1_amd64.deb 
(Reading database ... 43052 files and directories currently installed.)
Preparing to replace grub-common 1.99-21ubuntu3+zfs1 (using grub-common_1.99-21ubuntu3+zfs1_amd64.deb) ...
Unpacking replacement grub-common ...
Setting up grub-common (1.99-21ubuntu3+zfs1) ...
Processing triggers for ureadahead ...
root@ubuntu:/# dpkg -i grub-pc_1.99-21ubuntu3+zfs1_amd64.deb grub-gfxpayload-lists_0.6_amd64.deb 
(Reading database ... 43052 files and directories currently installed.)
Preparing to replace grub-pc 1.99-21ubuntu3+zfs1 (using grub-pc_1.99-21ubuntu3+zfs1_amd64.deb) ...
Unpacking replacement grub-pc ...
Preparing to replace grub-gfxpayload-lists 0.6 (using grub-gfxpayload-lists_0.6_amd64.deb) ...
Unpacking replacement grub-gfxpayload-lists ...
Setting up grub-pc (1.99-21ubuntu3+zfs1) ...
grub-probe: error: cannot find a device for / (is /dev mounted?).
grub-probe: error: cannot find a device for /boot (is /dev mounted?).
Installation finished. No error reported.
Installation finished. No error reported.
/usr/sbin/grub-probe: error: cannot find a device for / (is /dev mounted?).
dpkg: error processing grub-pc (--install):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of grub-gfxpayload-lists:
 grub-gfxpayload-lists depends on grub-pc (>= 1.99~20101210-1ubuntu2); however:
  Package grub-pc is not configured yet.
dpkg: error processing grub-gfxpayload-lists (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 grub-pc
 grub-gfxpayload-lists
root@ubuntu:/# dpkg -i grub-pc-bin_1.99-21ubuntu3+zfs1_amd64.deb 
(Reading database ... 43052 files and directories currently installed.)
Preparing to replace grub-pc-bin 1.99-21ubuntu3+zfs1 (using grub-pc-bin_1.99-21ubuntu3+zfs1_amd64.deb) ...
Unpacking replacement grub-pc-bin ...
Setting up grub-pc-bin (1.99-21ubuntu3+zfs1) ...

**Comment by treykyle** [comment]
So starting from scratch the packages appear to install correctly, now grub doesn't recognize my drive's filesystem to install to.  

root@ubuntu:/# grub-install /dev/disk/by-id/usb-PNY_USB_2.0_FD_00000000327AA39B-0:0
/usr/sbin/grub-probe: error: unknown filesystem.
Auto-detection of a filesystem of /dev/sdi2 failed.
Try with --recheck.
If the problem persists please report this together with the output of "/usr/sbin/grub-probe --device-map="/boot/grub/device.map" --target=fs -v /boot/grub" to bug-grub@gnu.org

**Comment by dajhorn** [comment]
Run the command in the error message:  `/usr/sbin/grub-probe --device-map="/boot/grub/device.map" --target=fs -v /boot/grub`.

Also run `grub-probe -vvv /` inside the chroot.

Post the results to http://gist.github.com/ if they are large.
