### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by Zodling** [zfsonlinux/pkg-zfs#6]
ubuntu server 11.04 
clean install 

after installing from the ppa i get an error like this when  "zpool list"

Failed to load ZFS module stack.
Load the module manually by running 'insmod <location>/zfs.ko' as root.

then i do/get this 

 sudo insmod /var/lib/dkms/zfs/0.6.0.25.rc5/$(uname -r)/x86_64/module/zfs.ko
insmod: error inserting '/var/lib/dkms/zfs/0.6.0.25.rc5/2.6.38-8-server/x86_64/module/zfs.ko': -1 Unknown symbol in module

PS: sorry about my bad english

**Comment by dajhorn** [comment]
Use `modprobe` instead of `insmod` like this:

```
$ sudo modprobe zfs
```

If this command fails, then please post the output of `dkms status` and `dmesg` to this ticket.

**Comment by Zodling** [comment]
worked perfectly
me and my server thank you 100 fold

an added note
i found it would not compile without errors unless i had followed the directions on pre-requirements on
http://zfsonlinux.org/spl-building-deb.html
http://zfsonlinux.org/zfs-building-deb.html
maybe the package "ubuntu-zfs" is missing some dependencies?
either way its up and running now thank you very much

**Comment by dajhorn** [comment]
The linux-headers-server package was likely the missing dependency.

By design, the DKMS infrastructure lets this happen in some circumstances.  It is most frequent on minimalistic non-default system installations.
