### ISSUE TITLE
os-prober with many zvols/snapshots makes upgrades painful

### ISSUE THREAD

**Issue by pdf** [zfsonlinux/pkg-zfs#62]
I store VMs on zvols, and use zfs-auto-snapshot to provde point-in-time rollback.  As a result, I current have ~1400 /dev/zd\* device nodes.  The result is horrendous behaviour from os-prober at kernel/grub update, since it tries to mount them all.

My current hack-around is just to patch /usr/bin/os-prober ignore devs with major 230, but I'm open to more sensible options if anyone has any.  I do think os-prober is going to need patching though...

**Comment by dajhorn** [comment]
There might be a way to avoid patching os-prober because this logic is in the `/etc/grub.d/30_os-prober` file:

```
OSPROBED="`os-prober | tr ' ' '^' | paste -s -d ' '`"
if [ -z "${OSPROBED}" ] ; then
  # empty os-prober output, nothing doing
  adjust_timeout
  exit 0
fi
```

Installing a dummy test to `/usr/lib/os-prober` that emits an empty result for zvols could short the os-probe test series.

**Comment by pdf** [comment]
> Installing a dummy test to /usr/lib/os-prober that emits an empty result for zvols could short the os-probe test series.

Good call, here's what I'm using now (`/usr/lib/os-probes/10zvol-test`):

``` sh
#!/bin/sh
# Sub-test to exclude ZVOLs
set -e
partition="$1"

. /usr/share/os-prober/common.sh

if [ "$(stat -L -c %t "$partition")" = "e6" ] ; then
        debug "$1 is a ZVOL; skipping"
        exit 0
fi

# No ZVOLs found
exit 1
```

**Comment by dajhorn** [comment]
I added this test and credited you.

**Comment by pdf** [comment]
Thanks Darik

**Comment by pdf** [comment]
On small change required - this needs to be chmod'd +x

**Comment by dajhorn** [comment]
Thanks.  I squeaked it into rc13.
