### ISSUE TITLE
spl-dkms build fails before libc6-dev is set up

### ISSUE THREAD

**Issue by nedbass** [zfsonlinux/pkg-zfs#64]
I ran into a glitch while testing the "HOWTO install Ubuntu to a Native ZFS Root Filesystem" procedure on Ubuntu 12.04.  During the DKMS build of SPL in the chroot'd environment, configure encountered the following error:

configure:3381: checking whether the C compiler works
configure:3403: gcc    conftest.c  >&5
/usr/bin/ld: cannot find crt1.o: No such file or directory
/usr/bin/ld: cannot find crti.o: No such file or directory
/usr/bin/ld: cannot find -lc
/usr/bin/ld: cannot find crtn.o: No such file or directory
collect2: ld returned 1 exit status

I worked around this by installing libc6-dev before 'apt-get install ubuntu-zfs'.

The unmodified procedure worked for me the first time I tried it a few days ago.  I suspect but have not verified that https://github.com/dajhorn/pkg-zfs/commit/19b6634 is the relevant
change.  Here is a transcript of the failure:

https://gist.github.com/4235942

**Comment by dajhorn** [comment]
This looks like one of the latent bugs in Precise that became more apparent in Quantal.  Commit 19b663484e0273fd3ca6e062eb4d64706f546973 seems to provoke it by changing the unpack order, which shouldn't matter.

This glitch should resolve when I publish the ubuntu-zfs that depends on build-essential.  That might happen this weekend, and if not, then I will update the tutorial.

**Comment by dajhorn** [comment]
The ubuntu-zfs-7~precise release does indeed resolve this glitch.

(Thanks for the report.)

**Comment by yarikdot** [comment]
The same problem is on debian jessie. How to simulate:
- download debian minimal iso
- add zfsonlinux repository
- aptitude install debian-zfs
  (exacly as stated here http://zfsonlinux.org/debian.html)

After installing libc6-dev it worked.
