### ISSUE TITLE
mountall: unclean shutdown causes all ZFS mounts to be ignored

### ISSUE THREAD

**Issue by wrouesnel** [zfsonlinux/pkg-zfs#70]
This is a follow up (though ultimately a different problem) to #66.

The basic issue is that my ZFS filesystems only successfully mount every second boot. To track down the cause I peppered the `parse_zfs_list` function wit nih_debug statements, and discovered the cause of my troubles:

```
parse_zfs_list: zfs_name: hddpool/var 
parse_zfs_list: zfs_mountpoint: /hddpool/var 
parse_zfs_list: zfs_canmount: on 
parse_zfs_list: zfs_mounted: yes

parse_zfs_list: zfs_name: hddpool/var/cache 
parse_zfs_list: zfs_mountpoint: /hddpool/var/cache 
parse_zfs_list: zfs_canmount: on 
parse_zfs_list: zfs_mounted: yes

parse_zfs_list: zfs_name: hddpool/var/cache/apt-cacher-ng 
parse_zfs_list: zfs_mountpoint: /var/cache/apt-cacher-ng 
parse_zfs_list: zfs_canmount: on 
parse_zfs_list: zfs_mounted: yes

parse_zfs_list: zfs_name: ssdpool 
parse_zfs_list: zfs_mountpoint: /ssdpool 
parse_zfs_list: zfs_canmount: on 
parse_zfs_list: zfs_mounted: yes
```

The basic issue is every filesystem is marked as mounted, because `zfs list` apparently just does a simple parse of mtab to determine if a filesystem is mounted, and so mountall incorrectly skips all the filesystems (because mtab still contains old entries).

This seems like the wrong behavior because any type of unclean shutdown situation leads to the ZFS filesystems not being mounted at boot up, yet there's never any reason not to try normally.

I'm guessing my ongoing experience with this is related to a fairly long-standing [Ubuntu bug](https://bugs.launchpad.net/ubuntu/+source/network-manager/+bug/1058987), causing unclean shutdowns, but even without it it's a fairly significant problem.

I'm currently playing with the mountall parse_zfs_list logic to see if this check can simply be ignored safely, since mountall already has it's own logic for checking if a mountpoint is already mounted.

**Comment by wrouesnel** [comment]
Testing with a virtual machine, the following patch to mountall from the PPA fixes the problem:

```
Index: mountall-2.42ubuntu0.2/src/mountall.c
===================================================================
--- mountall-2.42ubuntu0.2.orig/src/mountall.c  2012-12-28 00:23:39.129168000 +1100
+++ mountall-2.42ubuntu0.2/src/mountall.c   2012-12-28 00:24:21.616405000 +1100
@@ -773,7 +773,7 @@
    size_t bufsz = 4096;
    FILE *zfs_stream;
    const char zfs_command[] =
-     "/sbin/zfs list -H -t filesystem -o name,mountpoint,canmount,mounted";
+     "/sbin/zfs list -H -t filesystem -o name,mountpoint,canmount";
    int zfs_result;

    nih_debug ("parsing ZFS list");
@@ -792,7 +792,7 @@
    /* Read one line from the pipe into the buffer. */
    while (fgets (buf, bufsz, zfs_stream) != NULL) {
        char *saveptr;
-       char *zfs_name, *zfs_mountpoint, *zfs_canmount, *zfs_mounted;
+       char *zfs_name, *zfs_mountpoint, *zfs_canmount;

        /* If the line didn't fit, then enlarge the buffer and retry. */
        while ((! strchr (buf, '\n')) && (! feof (zfs_stream))) {
@@ -815,17 +815,11 @@
        }

        /* ASSERT: canmount = on | off | noauto */
-       zfs_canmount = strtok_r (NULL, "\t", &saveptr);
+       zfs_canmount = strtok_r (NULL, "\t\n", &saveptr);
        if (! zfs_canmount || strcmp (zfs_canmount, "on")) {
            continue;
        }

-       /* ASSERT: mounted = yes | no */
-       zfs_mounted = strtok_r (NULL, "\t\n", &saveptr);
-       if (! zfs_mounted || strcmp (zfs_mounted, "no")) {
-           continue;
-       }
-
        new_mount (zfs_mountpoint, zfs_name, FALSE, "zfs", "zfsutil,nobootwait");
    }


```

AFAIK the `mounted` check is unnecessary (and the problem), since mountall checks if the mountpoints are already mounted before it spawns a mount job - but zfs list checks mtab before it's been written by mountall (and any stale mountpoints get misrepresented). Removing that check, everything seems to work fine (mounts correctly on startup,  doesn't overmount things when run from the command line in a running session).

The patch is formatted to apply as a quilt patch after the zfs-linux.patch in mountall.

**Comment by dajhorn** [comment]
> Testing with a virtual machine, the following patch to mountall from the PPA fixes the problem

Thanks.  I will test this on my workstation.

> AFAIK the mounted check is unnecessary (and the problem), since mountall checks if the mountpoints are already mounted before it spawns a mount job - but zfs list checks mtab before it's been written by mountall (and any stale mountpoints get misrepresented).

Could you run `ln -sf /proc/mounts /etc/mtab` and check whether you get the same behavior?

IIRC, this behavior varies between `mountall` versions.  The `zfs-initramfs.preinst` does this for root installations, but I've been thinking about doing it for all installations.

**Comment by wrouesnel** [comment]
`ln -sf /proc/mounts /etc/mtab` does indeed resolve the problem using the normal mountall (tested in qemu/kvm). That is - it mounts every time.

**Comment by dajhorn** [comment]
This patch is published to the daily PPA for Precise and Quantal.

**Comment by dajhorn** [comment]
This patch is promoted to the stable PPA for Precise and Quantal.
