### ISSUE TITLE
Add configurable sleep timer to init scripts

### ISSUE THREAD

**Issue by tigloo** [zfsonlinux/pkg-zfs#71]
This is a feature request for mpt2sas users that see drives coming online only several seconds after the driver loaded:

Since I'm using ZFS as root file system, I had to change /usr/share/initramfs/scripts/zfs to include a sleep statement before wait_for_udev. However, since that file is not marked as a configuration file, changes are overwritten when upgrading the package.

Looking at the issues, it seems that there are several places where sleep statements can be used / should be used.

Would it be possible to factor the delay out into a configuration file that resides in /etc? Then all scripts could include a "sleep $ZFS_DRIVE_DELAY" line and the delays would survive upgrading the packages.

**Comment by dajhorn** [comment]
This enhancement is now in the daily PPA.  See the new `ZFS_INITRD_PRE_MOUNTROOT_SLEEP` option at the bottom of the `/etc/default/zfs` file.
