### ISSUE TITLE
HowTo is broken

### ISSUE THREAD

**Issue by d24m** [zfsonlinux/pkg-zfs#74]
The HowTo is broken because of the new ZFS Version 5000.

zpool create rpool /dev/disk/by-id/scsi-SATA_disk1-part2

creates a new zpool with zfs V5000 inside, which breaks grub-probe:

grub-probe /
grub-probe: error: unknown filesystem.

To solve this you can set the correct version via

zpool create -o version=28 rpool /dev/disk/by-id/scsi-SATA_disk1-part2

zpool upgrade -a (V28 -> V5000) on a running system with ZFS-root-filesystems also breaks grub-probe / grub-update / grub.cfg / zfs-bootfs and the system is not booting anymore

**Comment by dajhorn** [comment]
Updated. Thanks.

Note that `ashift=12` causes similar problems.
