### ISSUE TITLE
ZFS and its fun issues :)

### ISSUE THREAD

**Issue by Alvinator** [zfsonlinux/pkg-zfs#76]
This is in regards to https://github.com/dajhorn/pkg-zfs/wiki/HOWTO-install-Ubuntu-to-a-Native-ZFS-Root-Filesystem

I'll start out by saying I'm trying to do this on a 40GB sata drive for starts, then use a few 3TB+ drives for storage/data pools.

I tried this all initially with 12.10 but that wasn't going so well because I would get stuck with that python thing not installing but eventually learned how to get around that (those several) problems and reach the next point I am stuck with.  (the 12.10 solution was very much trial and error so I _could_ figure out instructions if someone wants them).  Anyways, long story short I gave up with 12.10 and figured I could upgrade from 12.04 to 12.10 later any time, so I tried to follow the guide exactly, but ran into the same issue at 6.1b.  I then tried verifying that the disk was in MBR format, then repeating, same problem.  Tried with GPT, same problem.  I am at a loss at what to try for this as I have been stuck on it two days now, I should probably mention that this is my first real experience with Ubuntu, as I was a Windows guy until I recently decided it was crap compared to ZFS+Ubuntu, plus I like the Ubuntu-Studio lowlatency kernel ;)

That reminds me, I'm doing this from a studio 12.04 disk, don't know if that would make much difference.

THANKS in advance for any input, and please forgive my noobfulness if you have to deal with any...

Here are the outputs requested from the tutorial:

root@ubuntu-studio:/# ls /boot/grub/zfs*
ls: cannot access /boot/grub/zfs*: No such file or directory
root@ubuntu-studio:/# apt-add-repository ppa:zfs-native/grub
You are about to add the following PPA to your system:
 The GRUB boot loader linked against libzfs for Linux.

Only use this PPA on Ubuntu systems that have a native ZFS root filesystem.  This PPA is incompatible with regular Debian systems.
 More info: https://launchpad.net/~zfs-native/+archive/grub
Press [ENTER] to continue or ctrl-c to cancel adding it

Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --secret-keyring /tmp/tmp.hetgyfUUmj --trustdb-name /etc/apt/trustdb.gpg --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver hkp://keyserver.ubuntu.com:80/ --recv E871F18B51E0147C77796AC81196BA81F6B0FC61
gpg: requesting key F6B0FC61 from hkp server keyserver.ubuntu.com
gpg: key F6B0FC61: "Launchpad PPA for Native ZFS for Linux" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
root@ubuntu-studio:/# apt-get update
Ign http://archive.ubuntu.com precise InRelease
Ign http://ppa.launchpad.net precise InRelease
Ign http://ppa.launchpad.net precise InRelease
Hit http://archive.ubuntu.com precise Release.gpg
Hit http://ppa.launchpad.net precise Release.gpg
Hit http://archive.ubuntu.com precise Release
Hit http://ppa.launchpad.net precise Release.gpg
Hit http://archive.ubuntu.com precise/main amd64 Packages
Hit http://ppa.launchpad.net precise Release
Hit http://ppa.launchpad.net precise Release  
Hit http://ppa.launchpad.net precise/main Sources
Hit http://ppa.launchpad.net precise/main amd64 Packages
Hit http://ppa.launchpad.net precise/main i386 Packages
Ign http://ppa.launchpad.net precise/main TranslationIndex
Hit http://ppa.launchpad.net precise/main Sources
Hit http://ppa.launchpad.net precise/main amd64 Packages
Hit http://ppa.launchpad.net precise/main i386 Packages
Ign http://ppa.launchpad.net precise/main TranslationIndex
Hit http://archive.ubuntu.com precise/main i386 Packages
Hit http://archive.ubuntu.com precise/main TranslationIndex
Hit http://archive.ubuntu.com precise/main Translation-en
Ign http://ppa.launchpad.net precise/main Translation-en_US
Ign http://ppa.launchpad.net precise/main Translation-en
Ign http://ppa.launchpad.net precise/main Translation-en_US
Ign http://ppa.launchpad.net precise/main Translation-en
Reading package lists... Done
root@ubuntu-studio:/# apt-get install --reinstall zfs-grub
Reading package lists... Done
Building dependency tree  
Reading state information... Done
Note, selecting 'grub-common' instead of 'zfs-grub'
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.
Need to get 0 B/2,355 kB of archives.
After this operation, 0 B of additional disk space will be used.
Can not write log, openpty() failed (/dev/pts not mounted?)
(Reading database ... 40489 files and directories currently installed.)
Preparing to replace grub-common 1.99-21ubuntu3.6+zfs1 (using .../grub-common_1.99-21ubuntu3.6+zfs1_amd64.deb) ...
Unpacking replacement grub-common ...
Processing triggers for ureadahead ...
Can not write log, openpty() failed (/dev/pts not mounted?)
Setting up grub-common (1.99-21ubuntu3.6+zfs1) ...
root@ubuntu-studio:/# apt-cache search zfs-grub
grub-common - GRand Unified Bootloader (common files)
root@ubuntu-studio:/# apt-cache show zfs-grub
N: Can't select versions from package 'zfs-grub' as it is purely virtual
N: No packages found
root@ubuntu-studio:/# apt-cache policy grub-common zfs-grub
grub-common:
  Installed: 1.99-21ubuntu3.6+zfs1
  Candidate: 1.99-21ubuntu3.6+zfs1
  Version table:
 **\* 1.99-21ubuntu3.6+zfs1 0
       1001 http://ppa.launchpad.net/zfs-native/grub/ubuntu/ precise/main amd64 Packages
        100 /var/lib/dpkg/status
     1.99-21ubuntu3 0
        500 http://archive.ubuntu.com/ubuntu/ precise/main amd64 Packages
zfs-grub:
  Installed: (none)
  Candidate: (none)
  Version table:
root@ubuntu-studio:/# 

..PS, how do you guys get all those nice and neat "code" boxes in your posts?? :)

**Comment by Alvinator** [comment]
Nevermind, I think I may have fixed it by looking at this dude's post over here https://github.com/dajhorn/pkg-zfs/issues/8
... I used apt-get install grub-pc

...and I think I found out my main cause of all issues, possibly, I've been putting "unmount" instead of "umount" for all of those type commands... finally caught up with me at the end.

Please don't close this thread yet as I may not be fully solved yet, I'll let you all (well, nobody atm) know when it works :)

**Comment by dajhorn** [comment]
> Anyways, long story short I gave up with 12.10 and figured I could upgrade from 12.04 to 12.10 later any time,

It is unlikely that Quantal will ever be supported in this configuration.  Upgrading from 12.04 to 12.10 will break the system.

The system must stay on Ubuntu 12.04 Precise if you want to run a native root pool.

**Comment by Alvinator** [comment]
Yeah I see that now :S  Oh well, I just got through sorting out my graphics issues with 3 cards and 4 monitors, ended up switching out the third nvidia card and leaving two ATI ones.  Worked like a charm after that :)

Anyways a mod can either close this thread OR leave it open for anyone else to comment on or maybe make it a goal for future development, somehow getting 12.10 to work with ZFS natively OR for the future like 13.04.

Another question, this about GRUB, does Grub 2.0 officially support ZFS?  Or does it still need to be modded to do so and does anyone know of any future of it doing so?  Thanks again.

**Comment by dajhorn** [comment]
> Another question, this about GRUB, does Grub 2.0 officially support ZFS?

It does support ZFS, but it does not accommodate all ZoL quirks or some recent Illumos features.  These patches were recently submitted upstream:
- http://lists.gnu.org/archive/html/grub-devel/2013-02/msg00003.html
- http://lists.gnu.org/archive/html/grub-devel/2013-02/msg00004.html
- http://lists.gnu.org/archive/html/grub-devel/2013-02/msg00005.html
- http://lists.gnu.org/archive/html/grub-devel/2013-02/msg00006.html
- http://lists.gnu.org/archive/html/grub-devel/2013-02/msg00007.html
- http://lists.gnu.org/archive/html/grub-devel/2013-02/msg00008.html

> Or does it still need to be modded to do so and does anyone know of any future of it doing so?

The package for Raring will probably need patching.  I will close this ticket when I publish it to the PPA.

>  Thanks again.

Welcome.

**Comment by dajhorn** [comment]
The PPA for Raring now has these patches. Please open new issue tickets for any new problems involving feature flags or version 5000 pools.
