### ISSUE TITLE
nfs4 filesystem in /etc/fstab

### ISSUE THREAD

**Issue by mk01** [zfsonlinux/pkg-zfs#78]
is blocking queue to endless loop again (if after other nodev filesystem follows). again the same dependency as there was existing for swap. 

nfs is remote filesystem, try_mount function is not called (that's right). but still the fs is going to queue immediately and during building the list the nodev strict dependency is created - if again nodev fs follows.

mk

**Comment by FransUrbo** [comment]
I'm going through old issues - is this a still issue? And exactly what IS the problem?

**Comment by mk01** [comment]
@FransUrbo 

late but counts! huh ;)

as this was year ago, I can just in general: it was all related to the mountall looping endlessly under some conditions - thus making boot practically fail (not continue by issuing "mounted filessystems/virtual/etc).

this one was report to some patches by myself, @dajhorn and perception of the problem as being solved but unfortunately it wasn't.

mountall was still failing on simple combinations of "mount -t bind" and "mount -t nfs4" in /etc/fstab.

but to answer your question, if I remember correctly 1y ago it was mountall ~2.1x . I suppose this is long ago solved by going for higher version - with different logic in the core workflows.
