### ISSUE TITLE
dkms building fails in livecd + grub installation issues

### ISSUE THREAD

**Issue by maxximino** [zfsonlinux/pkg-zfs#79]
I suspect that there is a problem with dkms and zfs grub packages.
I've booted ubuntu-12.04.1-desktop-amd64.iso in a VM, and started literally following 

https://github.com/dajhorn/pkg-zfs/wiki/HOWTO-install-Ubuntu-to-a-Native-ZFS-Root-Filesystem 
I see that it has problems with building zfs modules:
http://pastebin.com/QkABX2a5
make.log content:
http://pastebin.com/EzcfMxUy

As if nothing happened, I've continued to follow the tutorial:
http://pastebin.com/74eP4JC8
Looks like that even grub has some problems. (grub-pc not installed?)

I noticed those issues because a ZFS newcomer got really discouraged from this :(

**Comment by dajhorn** [comment]
Okay, I will verify the HOWTO when I merge your GRUB patches into the PPA.

The "Latest Tested Version" is when I last did a complete run of the tutorial.

**Comment by maxximino** [comment]
I understand the problem :) But those versions aren't available anymore in the PPA, right? What about creating ppa:zfs-native/safe-for-native-root-tutorial ?

**Comment by dajhorn** [comment]
Right, and that would be reasonable.  Maybe we will do that when the officially stable release happens and things won't change for a long time.

**Comment by thecabinet** [comment]
Hey, this is the problem I'm having too!  So there's no way to setup ZFS root right now?

**Comment by dajhorn** [comment]
@thecabinet,  the HOWTO instructions might work if you install `linux-image-generic` and `linux-headers-generic` before Step 5.6 in the chroot.  You can still install the `linux-image-virtual` and `linux-headers-virtual` after the system is bootstrapped if you still want them.

I will check the tutorial after I refresh the GRUB package with feature flags support.

**Comment by dajhorn** [comment]
I did a run through the tutorial and updated it for the 0.6.0.97-rc14 build.

The `dpkg: warning: version '*-*' has bad syntax: version number does not start with digit` line happens because the latest bootstrap manifest does not install a kernel.

Closed by: https://github.com/zfsonlinux/pkg-zfs/wiki/HOWTO-install-Ubuntu-to-a-Native-ZFS-Root-Filesystem/4438992f64d74679ee6f45760e2510752060b3b6
