### ISSUE TITLE
Grub trying to decompress when it shouldn't

### ISSUE THREAD

**Issue by adrianratnapala** [zfsonlinux/pkg-zfs#80]
After a reboot of a system that been successfully using ZFS for Linux on root, GRUB gets stuck with the error 

```
    error: lzjb decompression failed.
    error: you need to load the kernel first.

    Press any key to continue...
```
- Initial installation followed: https://github.com/zfsonlinux/pkg-zfs/wiki/HOWTO-install-Ubuntu-to-a-Native-ZFS-Root-Filesystem
- The grub menu appears normally, the error above appears immediately after trying to boot any kernel in the menu.
- This is grub-zfs 1.99

I do not know if this should really be reported to zfs-pkg, ZFS on Linux, or to the GRUB developers.  I am writing here because of a related discussion (https://github.com/zfsonlinux/pkg-zfs/issues/51) :

```
  > it just assumes something is compressed due to reading 
  > garbage data which happens to have the same header?

  This is a latent bug in the GRUB code that we have been unable to
  diagnose. Sometimes it works, and sometimes it doesn't. YMMV.
```

Is this relevant to the above error? Are there workarounds?  Is there a URL for where this bug is tracked?

The Troubleshooting section of the HOWTO warns that the /boot should not be on a compressed zpool, but this zpool is not compressed, since it would never have worked otherwise.

**Comment by dajhorn** [comment]
> I do not know if this should really be reported to zfs-pkg, ZFS on Linux, or to the GRUB developers. I am writing here because of a related discussion

This is probably the best place for it.

> Is this relevant to the above error? Are there workarounds? Is there a URL for where this bug is tracked?

This is a new mode of failure for grub2-1.99 if the compression property or the compression feature flag has never been enabled on the affected pool.  Maybe GRUB is confusing some bad data for an lzjb block.

First, scrub the pool using a LiveCD.  If you can, then try an Illumos LiveCD to additionally isolate for ZoL quirks.

Second, troubleshoot by refreshing the grub modules, reinstalling the loader, and updating the boot menu at a chroot rescue prompt like this:

```
# cp /usr/lib/grub/i386-pc/*.mod /boot/grub
# grub-install /dev/MyBootDisk
# update-grub
```

If the problem persists, then try the latest upstream GRUB2 release.  I will publish updated packages in the next few weeks, but not in time to help you with this problem.

Some pools age in a way that confuses GRUB.  If this happens, then the best solution is to move all of `/boot` into the regular filesystem.  Unfortunately, I would need the affected dataset in hand to properly diagnose this kind of problem.

**Comment by adrianratnapala** [comment]
Scrubbing the pool did in fact fix our immediate problem, so as you suggest, perhaps GRUB saw some garbage and got confused.  But this still seems like a problem with GRUB: a totally inscrutable error message in the face of bad but recoverable data.  Obviously GRUB can't protect against every perverse case of bad data, but it still seems work looking at.

Given that scrubbing helped is there any value  immediate

Thanks for the response.   Sorry for being slow in our response.

**Comment by dajhorn** [comment]
No, there is nothing else to do.  Thanks for the bug report.

I will leave this ticket open until the PPA is updated.

**Comment by dajhorn** [comment]
Given that GRUB significantly improved OpenZFS support upstream, and that the PPA is in legacy maintenance, I will close this ticket.
