### ISSUE TITLE
lintian: script-not-executable

### ISSUE THREAD

**Issue by dajhorn** [zfsonlinux/pkg-zfs#83]
Lintian is reporting this warning for the current build series:

```
W: zfs-dkms: script-not-executable usr/src/zfs-0.6.1/cmd/zpool_id/zpool_id
W: zfs-dkms: script-not-executable usr/src/zfs-0.6.1/cmd/zpool_layout/zpool_layout
```

**Comment by behlendorf** [comment]
That's a bit confusing, both of these scripts were retired.

**Comment by dajhorn** [comment]
The PPA is still carrying those components because some important sites are using them.  I decided that automatically converting the configuration was too risky to do near a release deadline.

Finishing the interface change is something that I will do for the next series.

**Comment by FransUrbo** [comment]
Not reported in Debian GNU/Linux Wheezy packages.

**Comment by dajhorn** [comment]
Stale, and now handled downstream.
