### ISSUE TITLE
lintian: shell-script-fails-syntax-check

### ISSUE THREAD

**Issue by dajhorn** [zfsonlinux/pkg-zfs#84]
Lintian is reporting this error for the current build series:

```
E: zfs-dkms: shell-script-fails-syntax-check usr/src/zfs-0.6.1/cmd/zpool_layout/zpool_layout
```

This code is unused by DKMS and should not be installed with the module source code.

**Comment by FransUrbo** [comment]
Not reported in Debian GNU/Linux Wheezy packages.

**Comment by dajhorn** [comment]
Stale, and now handled downstream.
