### ISSUE TITLE
zfs-initramfs should not depend on mountall

### ISSUE THREAD

**Issue by dajhorn** [zfsonlinux/pkg-zfs#9]
The mountall utility is not in the regular initrd manifest for Ubuntu, and it is not used to start a native ZFS root filesystem.  

Depending on mountall unnecessarily prevents zfs-initramfs from being installed on vanilla Debian systems.

**Comment by rlaager** [comment]
Does the ef6fcd1 commit mean this issue can be closed?

**Comment by dajhorn** [comment]
No, because I forgot to merge it into the latest point release.  It is in the pkg-zfs master now, so Github should automatically close it.

**Comment by dajhorn** [comment]
Closed by: dajhorn/pkg-zfs@48d9267a6abd53a2abda54c746711111e94c575d
