### ISSUE TITLE
update-initramfs complains about zpool_id with zfs 0.6.1

### ISSUE THREAD

**Issue by yacoob** [zfsonlinux/pkg-zfs#90]
update-initramfs fails with:

```
# update-initramfs -k all -u
update-initramfs: Generating /boot/initrd.img-3.8.4
Error: /lib/udev/zpool_id is not executable.
E: /usr/share/initramfs-tools/hooks/zdev failed with return 2.
```

This is probably related to the fact that [zpool_id got retired](https://github.com/zfsonlinux/zfs/issues/981). 

That's with zfsutils built from [this commit](https://github.com/zfsonlinux/pkg-zfs/commit/d941cd3dfde0fff0a03e947186eafbbef0fc9614).

**Comment by dajhorn** [comment]
> This is probably related to the fact that zpool_id got retired.

That change should be reverted by `debian/patches/0001-Revert-Retire-zpool_id-infrastructure.patch` in the packaging, which means that the `/lib/udev/zpool_id` file should still be installed by the zfsutils package.

> update-initramfs: Generating /boot/initrd.img-3.8.4

None of wheezy, precise, quantal, or raring are currently shipping that kernel version;  linux-image-3.8.0-15-generic is the latest that I've got on my machines.

What is the output of `lsb_release -a`?

What is the output of `apt-cache policy zfsutils`?

**Comment by yacoob** [comment]
Hm, indeed, the patch should have been applied. It wasn't, when I've built the package with `fakeroot ./debian/rules binary`. I'm now rebuilding the package with `debuild -i -us -uc -b`, and it seems to have been applied. Looks like it's a case of PEBKAC. :D 

As for the kernel: it's my own build of 3.8.4 packaged with `make-kpkg` on Debian stable:

```
# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 6.0.7 (squeeze)
Release:        6.0.7
Codename:       squeeze
```

Let me rebuild the packages and see if it behaves as expected. I believe it will - once I verify this, I'll close this bug.

Last but not least: are there any plans of merging `pkg-zfs` with `zfs` repository proper?

**Comment by yacoob** [comment]
Yup, `zpool_id` is there. Mea culpa. Sorry for a false alarm.

**Comment by dajhorn** [comment]
> Hm, indeed, the patch should have been applied. It wasn't, when I've built the package with fakeroot ./debian/rules binary. I'm now rebuilding the package with debuild -i -us -uc -b, and it seems to have been applied.

Okay, good to know.

> are there any plans of merging pkg-zfs with zfs repository proper?

No.  As downstream ZoL integration has improved, @behlendorf has removed packaging elements from the zfsonlinux/zfs repository.  It is more likely that zfsonlinux/pkg-zfs will be retired entirely if Debian and/or Ubuntu bundle ZoL in regular distribution, or that it will exist only to dispatch daily builds.

**Comment by yacoob** [comment]
Allright. For the moment I don't have a problem with building a new version of modules every now and then, it's just small hiccups like above I bump into. Is there an analogue of [this PPA](https://launchpad.net/~zfs-native/+archive/stable) for Debian? Ie. builds of release versions of spl+zfs debs for Debian stable?

**Comment by dajhorn** [comment]
> Is there an analogue of this PPA for Debian?

Yes, you can put this into a `/etc/apt/sources.list.d/zfsonlinux.list` file:

```
deb http://archive.zfsonlinux.org/debian wheezy main
deb-src http://archive.zfsonlinux.org/debian wheezy main
```

But there are no plans to build specifically for Debian 6 now that Debian 7 is in release freeze. Note that you'll need to manually import the DC0FCB63 key into the system keyring until these packages are fully polished.

**Comment by yacoob** [comment]
Cool. I guess I'll start using this once I move to wheezy proper. Thanks for the help and information :)
