### ISSUE TITLE
/boot/grub/zfs.mod  /boot/grub/zfsinfo.mod for installing Ubuntu 13.04 native root & grub

### ISSUE THREAD

**Issue by minhgi** [zfsonlinux/pkg-zfs#92]
Hello There,

I am new to linux but experience enough to install a native root zfs for Ubuntu 12.04 with a graphical desktop.  When I saw that 13.04 grub was release, I follow the guide for 12.04 to install a fresh copy of 13.04 beta 2.  Everything went fine except when I got to step 6.1.

At step 6.1, I was able to get the # grub-probe / to show zfs was install to grub successfully.  However, when I got to # ls /boot/grub/zfs_, both mod was missing.  It say ls: cannot access /boot/grub/zfs_: No such file or directory

What could be the problem?  I had no problem with installing 12.04 but 13.04 was pain.

**Comment by blair** [comment]
In 13.04 I think they are all in /boot/grub/i386-pc instead.

**Comment by minhgi** [comment]
It seem like I need to learn more about the grub configuration.  Following the below mail discussion show that grub.cfg was getting it config else where and it was wrong.  

http://osdir.com/ml/zfs-discuss/2013-05/msg00000.html
