### ISSUE TITLE
update guide to native zfs root from Ubuntu 12.04 to final 13.04

### ISSUE THREAD

**Issue by minhgi** [zfsonlinux/pkg-zfs#96]
Hello,

Will there be an updated guide for native zfs root Ubuntu since it is now in final stage?  I have trouble with installing a new install of Ubuntu 13.04 with the 12.04.2 guide.   I seem to run into the reboot problem where grub2 can not found root file and load the kernel.

I am itching to get this working.

Thanks

**Comment by minhgi** [comment]
This is what I get from grub.cfg

root@ubuntu:/# grep boot=zfs /boot/grub/grub.cfg
    linux   /ROOT/ubuntu-1/@/ROOT/ubuntu-1@//boot/vmlinuz-3.8.0-19-generic root=ZFS=rpool/ROOT/ubuntu-1/@/ROOT/ubuntu-1 ro boot=zfs $bootfs   quiet splash $vt_handoff
        linux   /ROOT/ubuntu-1/@/ROOT/ubuntu-1@//boot/vmlinuz-3.8.0-19-generic root=ZFS=rpool/ROOT/ubuntu-1/@/ROOT/ubuntu-1 ro boot=zfs $bootfs   quiet splash $vt_handoff
        linux   /ROOT/ubuntu-1/@/ROOT/ubuntu-1@//boot/vmlinuz-3.8.0-19-generic root=ZFS=rpool/ROOT/ubuntu-1/@/ROOT/ubuntu-1 ro single nomodeset boot=zfs $bootfs

**Comment by hendismurf1** [comment]
How did you solve the problem? Cause i´m running into the same when setting up an new ubuntu 13.04 zfs installation.

**Comment by rrossouw** [comment]
I had the same problem on Ubuntu 13.04 and only way to boot was to fix /boot/grub/grub.cfg.  To first boot just manually edit the grub boot entries.  I still saw a "missing label" error but it still boots.

I temporarily fixed two lines in /boot/grub/grub.cfg as follow for subsequent boots: 

_#linux  /ROOT/ubuntu-1/@/ROOT/ubuntu-1@//boot/vmlinuz-3.8.0-19-generic root=ZFS=rpool/ROOT/ubuntu-1/@/ROOT/ubuntu-1 ro boot=zfs $bootfs   quiet splash $vt_handoff_
**linux   /ROOT/ubuntu-1/@/boot/vmlinuz-3.8.0-19-generic root=/dev/sda2 ro boot=zfs $bootfs   quiet splash $vt_handoff**

_#initrd    /ROOT/ubuntu-1/@/ROOT/ubuntu-1@//boot/initrd.img-3.8.0-19-generic_
**initrd    /ROOT/ubuntu-1/@/boot/initrd.img-3.8.0-19-generic**

**Comment by dajhorn** [comment]
This is being worked on in zfsonlinux/zfs#1441.   This ticket seems to be accidentally closed, so I've reopened it.
