### ISSUE TITLE
Package arcstat.py separately.

### ISSUE THREAD

**Issue by dajhorn** [zfsonlinux/pkg-zfs#97]
The arcstat implementation imported at zfsonlinux/zfs@7634cd54db25a69e00aaab6448ad710441bd8e7d is a python script.

Create a sub-package or mask for this script so that the zfsutils package does not get an automatic python dependency.

**Comment by aarcane** [comment]
Being a python script is the primary reason this script was ported to Linux and included in the mainstream zfs package. All the major distros including ubuntu, zfs, and red hat, which zfs is packaged for include python in their most minimal install. For instance, if you debootstrap ubuntu, you get python installed. Therefore, this script can be included out of the box without need for additional requirements, which was one of the primary reasons cited in the initial pull request

**Comment by dajhorn** [comment]
Some important downstream sites would object to a python dependency, even though it is installed by default for regular installations.  Recall how Illumos rewrote all of the python code that was imported from Solaris.

Ideally, the new `arcstat.py` for ZoL would be included in the zfsutils package without causing an automatic dependency on the python interpreter for any build target.  There is probably a debhelper option or lintian override to do this, so conformance with both system policy and user expectations should be doable.

**Comment by aarcane** [comment]
Would it be possible to suggest python, since most package managers won't install suggested packages by default, and since the arcstat functionality is non essential?

**Comment by dajhorn** [comment]
Dunno, as I haven't yet reviewed the policy chapter for Python.  This issue should be investigated in time for the ZoL 0.6.2 release series, so feel free to do the research if you want things a particular way.

The goal here is to keep existing users happy and not install the python stack during an upgrade if they somehow don't already have it.

**Comment by behlendorf** [comment]
@dajhorn Ugh, I forgot about automatically generated dependencies.  Your right, this probably does need to go in to a sub-package in the upstream packaging as well, I'd also like to keep the core zfs bits free from a python dependency.

**Comment by dajhorn** [comment]
Canonical similarly omitted arcstat in the final Ubuntu 16.04 LTS release, so I will close this ticket.
